### ISSUE TITLE
Sync installed extensions via Google data storage

### ISSUE THREAD

**Issue by PeteLawler** [nE0sIghT/chrome-gnome-shell-mirror#10]
As Gnome don't seem to make it easy to sync extensions between browsers, it'd be great if this extension could utilise Google's native services to do such.

**Comment by nE0sIghT** [comment]
It's available in version 7

**Comment by PeteLawler** [comment]
Ah, right. Because of #11, the extension wasn't updating so I hadn't seen it. Now because of workaround mentioned in that ticket, I can see it. Excellent stuff, thanks!
