### ISSUE TITLE
extension not signed in Firefox 43+

### ISSUE THREAD

**Issue by demoklion** [nE0sIghT/chrome-gnome-shell-mirror#100]
> Starting with Firefox 43, add-on extensions and multi-item add-ons that include extensions need to be signed by Mozilla before they can install in release and beta versions of Firefox. 

[More info on mozilla's site](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/Distribution#Signing_your_add-ons)

**Comment by nE0sIghT** [comment]
I don't understand what do you want.  
However I can assume you hit:
https://bugzilla.mozilla.org/show_bug.cgi?id=1548973
https://github.com/mozilla/addons/issues/978

Reopen if you still think there is some chrome-gnome-shell related issue and give some explanation.

**Comment by demoklion** [comment]
oh, okay, didn't see that. 
My experience was different, but it seems fixing the mozilla bug will fix it for me too. Thanks
