### ISSUE TITLE
_usr_bin_gnome-shell.121.crash

### ISSUE THREAD

**Issue by xuemeizh** [nE0sIghT/chrome-gnome-shell-mirror#102]
every day when i start my laptop, comes out this report.

**Comment by nE0sIghT** [comment]
You should be more descriptive.
Start with some screenshots or crash logs or something.

**Comment by nE0sIghT** [comment]
Reopen if it's still issue

**Comment by Wu1069444514** [comment]
hello!Did you have solved this question?I have the same problem now
