### ISSUE TITLE
Connector crashing on Solaris

### ISSUE THREAD

**Issue by kulikjak** [nE0sIghT/chrome-gnome-shell-mirror#103]
Hi, I am yet unsuccessfully trying to make the connector running on Solaris with Firefox 68.5.0esr .

I placed the manifests into `/usr/lib/mozilla/native-messaging-hosts/org.gnome.chrome_gnome_shell.json` (which seems to be the only path where firefox finds the manifest and runs the native application), but when I start firefox, I get **undefined** on the website and the following error in the Browser Console:

    [1865] Uncaught exception of type <type 'exceptions.TypeError'> occured
      File "/usr/bin/chrome-gnome-shell", line 585, in <module>
        app = ChromeGNOMEShell(run_as_service)
      File "/usr/bin/chrome-gnome-shell", line 82, in __init__
        None)
    [1865] Exception: Argument 0 does not allow None as a value
    
    (process:1865): GLib-GIO-CRITICAL **: 18:10:14.213: g_application_release: assertion 'application->priv->use_count > 0' failed

Which is caused by `self.get_dbus_connection()` returning `None`. From my testing `self.get_dbus_object_path()` returns `None` as well. It seems like the `Gio.Application` dbus stuff is not being initialized or something like that (???).

The weird thing is that when I run `/usr/bin/chrome-gnome-shell` from the command line, it works (both with or without `sudo`).

Since I get something out, I think that my manifests are placed correctly.

**Comment by nE0sIghT** [comment]
Which version of GNOME is supplied with Solaris?

**Comment by kulikjak** [comment]
GNOME 3.24.0

**Comment by kulikjak** [comment]
I did some additional investigation and found out that the problem is caused by firefox not forwarding environment to subprocesses, meaning that `DBUS_SESSION_BUS_ADDRESS` is not in the environment and chrome-gnome-shell doesn't know where dbus should connect. Hence I am closing this, sorry for a false alarm :).
