### ISSUE TITLE
Native host has exited

### ISSUE THREAD

**Issue by Twiipy** [nE0sIghT/chrome-gnome-shell-mirror#104]
I haven't been able to open up the extension for a while now. I am currently in Ubuntu 20.04 LTS. The popup for the extension just has "Native host has exited."
And the console output when I open it from the terminal is:

```
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 16, in <module>
    from gi.repository import GLib, Gio
ImportError: No module named gi.repository
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 16, in <module>
    from gi.repository import GLib, Gio
ImportError: No module named gi.repository
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 16, in <module>
    from gi.repository import GLib, Gio
ImportError: No module named gi.repository
```
I found that some people had this same [issue ](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/20)some years ago, I tried everything still not able to get it working. Please let me know if there is any solution for this. Thank you,

**Comment by nE0sIghT** [comment]
```gi.repository``` module is missing in your install.  
Report this to Ubuntu maintainers.

**Comment by Twiipy** [comment]
> `gi.repository` module is missing in your install.
> Report this to Ubuntu maintainers.

Ok, thanks! I will
