### ISSUE TITLE
Causes excess CPU usage when installed on windows machine

### ISSUE THREAD

**Issue by osterhoutan** [nE0sIghT/chrome-gnome-shell-mirror#107]
I was having random spikes in CPU usage for about 2min every 10 or so min, for the past few days _(since installing this in my Chromium instance on my Linux distro [ubuntu], & it synced into my windows installation of Google Chrome)_.

To make sure that it was an issue with this extension, I did the following:
 1. I went ahead and I closed all open tabs and only had a new tab open then ended the task, before re-launching chrome.  
 2. Once it was up I waited for 30 min to make sure it happened again and **a CPU spike occurred within 10 min**.
 3. I opened `chrome://extensions/` and I disabled all extensions, waited 30 min to see if it happened, **the CPU did not spike in the 30 min**.
 4. I went through and tested each of my extensions starting with the most recently added, by enabling them and waiting for 30 min (not browsing or anything).  **When the _GNOME Shell Integrations_ extension was enabled did the CPU spike occur within 10 min of it being enabled.**
 5. To make sure it was this extension I re-enabled all other extensions I normally use and reopened the wep pages I was using before, and let it sit idle like it was before for another 30 min, and **no CPU Spike Occured**.

Hopefully it's just a simple issue with a check of the enviroment.

**Comment by nE0sIghT** [comment]
Please show screenshot of Chrome's task manager when "cpu spike" occurs.  
Actually you shouldn't even see GNOME Shell integration in Chrome's task manager because it doesn't run on Windows.

**Comment by nE0sIghT** [comment]
Reopen if it's still issue and provide requested info.
