### ISSUE TITLE
Chromium flatpak does not work

### ISSUE THREAD

**Issue by andreyddk** [nE0sIghT/chrome-gnome-shell-mirror#109]
Hi. Ext does not working in chromium installed from flatpak.

System:
Arch linux
Chromium Version 87.0.4280.141 (Official Build) (64-bit)

Error in extensions.gnome.org
`Although GNOME Shell integration extension is running, native host connector is not detected. Refer documentation for instructions about installing connector.`

**Comment by nE0sIghT** [comment]
Hi.

Please report this to Chromium flatpack package maintainers.

See also: 
https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1741074
https://forum.snapcraft.io/t/chrome-gnome-shell-does-not-work-with-chromium-snap/3377
https://gitlab.gnome.org/GNOME/chrome-gnome-shell/-/issues/5
etc
