### ISSUE TITLE
нативный хост-коннектор не обнаружен

### ISSUE THREAD

**Issue by XStanleyX** [nE0sIghT/chrome-gnome-shell-mirror#112]
Ubuntu 22.04, Gnome 42.1, Firefox 101.0.1, Chromium Версия 102.0.5005.115 (Официальная сборка), snap (64 бит) (ubuntu store), установлен пакет chrome-gnome-shell самой новой версии (10.1-5).

Ошибка: Хотя расширение GNOME Shell integration работает, нативный хост-коннектор не обнаружен.

**Comment by nE0sIghT** [comment]
Это - проблема snap: https://bugs.launchpad.net/bugs/1741074
