### ISSUE TITLE
Failed to build due to missing contrib/merge_json.py

### ISSUE THREAD

**Issue by soig** [nE0sIghT/chrome-gnome-shell-mirror#116]
Hi
I just tried to build the new 11.1 release but it failed to build due to missing contrib/merge_json.py:

```
Program 7z found: YES (/usr/bin/7z)
Program python3 found: YES (/usr/bin/python3)
Configuring manifest-chrome.json using configuration
Configuring manifest-firefox.json with command

meson.build:59:2: ERROR: Program or command 'chrome-gnome-shell-mirror-11.1/contrib/merge_json.py' not found or not executable
```

It looks like https://github.com/nE0sIghT/chrome-gnome-shell-mirror/archive/refs/tags/v11.1.tar.gz is incomplete…

**Comment by nE0sIghT** [comment]
It will be included in next tag. As for now please use master branch
