### ISSUE TITLE
Removing the extension

### ISSUE THREAD

**Issue by kuwood** [nE0sIghT/chrome-gnome-shell-mirror#12]
I am on ubuntu 16.04 and have tried removing the PPA and removing via apt-get remove but I cannot remove the extension as it is locked with "Installed by enterprise policy.". How can I remove this now? I have tried googling but it seems no one has ever ran into this issue? Please help.

**Comment by nE0sIghT** [comment]
Hi,

You should remove:
/etc/opt/chrome/policies/managed/chrome-gnome-shell.json
/etc/chromium/policies/managed/chrome-gnome-shell.json

**Comment by nE0sIghT** [comment]
Or use

`apt-get purge chrome-gnome-shell`

**Comment by kuwood** [comment]
Perfect thanks!
