### ISSUE TITLE
Policy files under /etc should be uninstalled by package manager

### ISSUE THREAD

**Issue by nE0sIghT** [nE0sIghT/chrome-gnome-shell-mirror#13]
Configuration files under /etc usually does not get removed by package manager.
All distro packages should explicitly remove chrome-gnome-shell policy files upon deinstallation:
```
/etc/opt/chrome/policies/managed/chrome-gnome-shell.json
/etc/chromium/policies/managed/chrome-gnome-shell.json
```

@josephgbr @region51

Please modify your packages to explicitly remove policy files.

See also: https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/12

**Comment by josephgbr** [comment]
Checked. This is not a problem for [Arch Linux users](https://aur.archlinux.org/packages/chrome-gnome-shell-git), as all files installed by [PKGBUILD](https://www.archlinux.org/pacman/PKGBUILD.5.html) are removed during the uninstall (that's a behavior of [pacman](https://www.archlinux.org/pacman/)).

**Comment by nE0sIghT** [comment]
Thanks

**Comment by region51** [comment]
@nE0sIghT привет, у меня с инглиш не очень, о чем речь? О то, я как раз хотел обновить до 7 версии.

**Comment by nE0sIghT** [comment]
@region51 Привет.

Начиная с 7 версии ставятся политики Chrome для принудительной установки расширения из Chrome store:
```
/etc/opt/chrome/policies/managed/chrome-gnome-shell.json
/etc/chromium/policies/managed/chrome-gnome-shell.json
```

В Debian/Ubuntu и Gentoo при удалении пакетов файлы в папке `/etc` не удаляются вместе с пакетом. В итоге если не удалять эти файлы принудительно вместе с пакетом, то становится невозможным удалить расширение из браузера.

Проверь, пожалуйста, что после удаления rpm пакета файлы политик также удаляются.
Если в Fedora/RHEL файлы в /etc по умолчанию не удаляются вместе с пакетом, то нужно делать это принудительно.

**Comment by region51** [comment]
а, да это не проблема.

**Comment by nE0sIghT** [comment]
Отлично, спасибо.
