### ISSUE TITLE
missing sources

### ISSUE THREAD

**Issue by rickysarraf** [nE0sIghT/chrome-gnome-shell-mirror#14]
You've already done most of the packaging. But I'm trying to bring it into Debian. Which would mean I need access to the sources for 2 files. Can you please provide those source files ?

```
rrs@learner:/var/tmp/Debian-Build/Result$ lintian chrome-gnome-shell_7.1-1_amd64.changes 
P: chrome-gnome-shell source: source-contains-prebuilt-javascript-object debian/missing-sources/jquery-2.1.4.min.js
E: chrome-gnome-shell source: source-is-missing debian/missing-sources/jquery-2.1.4.min.js
P: chrome-gnome-shell source: source-contains-prebuilt-javascript-object debian/missing-sources/tabby-10.1.0.min.js
E: chrome-gnome-shell source: source-is-missing debian/missing-sources/tabby-10.1.0.min.js
P: chrome-gnome-shell source: source-contains-prebuilt-javascript-object extension/include/external/jquery-2.1.4.min.js
E: chrome-gnome-shell source: source-is-missing extension/include/external/jquery-2.1.4.min.js
P: chrome-gnome-shell source: source-contains-prebuilt-javascript-object ... use --no-tag-display-limit to see all (or pipe to a file/program)
E: chrome-gnome-shell source: source-is-missing ... use --no-tag-display-limit to see all (or pipe to a file/program)
```

**Comment by rickysarraf** [comment]
BTW, the deb is only supposed to provide the connector, or the chrome plugin too ?

**Comment by nE0sIghT** [comment]
> BTW, the deb is only supposed to provide the connector, or the chrome plugin too ?

It's providing connector only.
Extension will be installed from Chrome store (for Chrome/Chromium/Vivaldi) by managed policy.

The reason why I can not package extension without Chrome store is the fact that every extension should be signed.
Signing process itself is not a problem - we can sign extension manually while building debsrc. However extension ID is calculated from public part of key used to sign extension.
And the main problem is that extensions with different IDs will have different settings (both local and remote - if you use sync feature).
On other side we can use some published private key, but I think that is bad idea.

**Comment by nE0sIghT** [comment]
> Can you please provide those source files ?

Done in master

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Wed, 2016-09-28 at 08:16 -0700, Yuri Konotopov wrote:
> It's providing connector only.
> Extension will be installed from Chrome store (for Chrome/Chromium/Vivaldi) by
> managed policy.
> 

THank you for the explanation. I will tweak the package description accordingly.
I really like your work in simplifying GNOME Shell Extension management from
Chromium browser.

> The reason why I can not package extension without Chrome store is the fact
> that every extension should be signed.
> Signing process itself is not a problem - we can sign extension manually while
> building debsrc. However extension ID is calculated from public part of key
> used to sign extension.
> And the main problem is that extensions with different IDs will have different
> settings (both local and remote - if you use sync feature).
> On other side we can use some published private key, but I think that is bad
> idea.


Thanks. That's good information to know.

> 
- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJX6+KxAAoJEKY6WKPy4XVp3OwQAK0vx3JKAWubIt44V/TfyLUi
nI7R4mTumIFfQwLKu94N+8G1t1c9aAmSZb8iG74xkrlJIGBdDA6Pr5o8tYhZkOZE
VSsFKlNuw5+YVOuYG/rydG8dqKwTmAEpfMkV86VYfhJWk5P6OOM2lXeLGb9qo+Tp
f1kR3CHrHPsI5+bYAmj/ydXtRpU25kUQ3Xc2WukWfaABDF6Pk09q7/cONHlDttGN
J02dxVPkoqnF7afGZuFvVwAF18Mp6a/HB85Jd8RZurUAHxM19fkFEKa6BzTFI2J/
LGjxZMKCiO1P4G0OV/QOe4sDGLxOlK6ufFzOwIrOWF2NjTn0JJqMz4ALA8Wu1OQt
yS0ikU3dgyIyN4rpHJfwat2piuod6Q16+urPvlCdG6Zunyo6H8oDmZrHaqVf6AfO
NL59C+abAnlE1NDmAK460EA30Y2xXiMQeUTR9PtjXTHE3oOauNr0Uu9m3Jdfd/2A
GA2q7VhB3BzknVzJjqIBopP/2zJID8To3PE7ho+PMNyW9b+AgQjhJhCvm9W34IVA
3iicImadTwBIzliQVezKONMW5PYSBM3K7oW+soUhDkhsVWaL+bWwYZDrny3RpFgo
UDW8HCDypmeYYXbDzXC2bEcx6VOX+4hSoSsxGRNcxpedqiRYHfawQHY4FGRIz4Vd
OJv0GJa5rh5yXGVD7zOD
=U7IV
-----END PGP SIGNATURE-----

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Wed, 2016-09-28 at 21:03 +0530, Ritesh Raj Sarraf wrote:
> On Wed, 2016-09-28 at 08:16 -0700, Yuri Konotopov wrote:
> > It's providing connector only.
> > Extension will be installed from Chrome store (for Chrome/Chromium/Vivaldi)
> by
> > managed policy.
> > 
> 
> THank you for the explanation. I will tweak the package description
> accordingly.
> I really like your work in simplifying GNOME Shell Extension management from
> Chromium browser.

So, just FYI, here's my final control file.


rrs@learner:~/rrs-home/Community/Packaging/chrome-gnome-shell (master)$ cat
debian/control.in 
Source: chrome-gnome-shell
Section: gnome
Priority: optional
Maintainer: Debian GNOME Maintainers <pkg-gnome-maintainers@lists.alioth.debian.
org> 
Uploaders: Ritesh Raj Sarraf <rrs@debian.org>, @GNOME_TEAM@
Build-Depends: debhelper (>= 9.0.0), cmake, python (>= 2.7), gnome-pkg-tools
Standards-Version: 3.9.8
Homepage: https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome
Vcs-Git: https://anonscm.debian.org/git/pkg-gnome/chrome-gnome-shell.git
Vcs-Browser: https://anonscm.debian.org/git/pkg-gnome/chrome-gnome-shell.git

Package: chrome-gnome-shell
Architecture: all
Depends: ${misc:Depends}, gnome-shell, python (>= 2.7), python-gi
Suggests: chromium
Description: GNOME Shell integration for Chromium browser
 Provides integration with GNOME Shell extensions repository for
 Chromium (and other derivaties) browser
 .
 This package provides the connector that talks with the browser
 extension


- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJX6+i+AAoJEKY6WKPy4XVpse0QAIJFYFGAIRfGRlQdOkyGmVHf
FtKjj62oGCaGCGVcuV01mwW60RGsnyL3QB5hIzEksoGmnx/xEuExF12E1qAyqWyF
BM+GHMyoRbRdVr8hRRgzC2vUEfPeRAGEQiV+68ySRwMXg+Y8TwUcQ7Ek04tOS10n
aZHbK97YYtnOefTrBUi8PPogkOjpxL6spt7ZM+OH7Corm4UoIT+udZqJDZhLQjQR
nVFA6HxGcyMjmff1+rm48QvpQwqGh1jculWRzrYRCf/EC2DtbQz5ybdjJowno/3f
eFz8mghkcMXFopdUD3r2K9btZHm5lM65j0oUf+qZxQ9GsLTnUQmcr/65r/wDqpO5
H+8AdcmSKPErNGJndl5U4QqgA48yk82hr7+yTOVGYc5qaiIs5vt//rPMY/2yGb1l
4Q8DoSGcpdA8JnwkhLzpiX0LidfPf0U9aeMNKBNM9/wJljlw0mNcLcnTl2jLhE3n
QnRmalQhuWLNzhS1ZhYpN3XZF0FEytRb3aT3W1UT4I5f1E67vdnl7XWWMbQ5UGLO
J7NhQ5I7X+kLzsmvP6hgbgrlqxL7y0f6vXI9YhZ3sES7CIHvgHCu93709qqdPNlN
jL1wndIvyUMqnyy7DafKsmloECuMprhg5mk9aVW9xkxto6wW7hkeR0dNKRFrdUE5
aNVY3C7gJ81tewK9G4VL
=9/W/
-----END PGP SIGNATURE-----
