### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by rickysarraf** [nE0sIghT/chrome-gnome-shell-mirror#15]
The package source has some translation files, with no license declaration. I realized this with pointers from Debian FTP team.

```
rrs@learner:~/rrs-home/Community/Packaging/chrome-gnome-shell (master)$ licensecheck -r po/
po//LINGUAS: *No copyright* UNKNOWN
po//README: *No copyright* UNKNOWN
po//ca.po: UNKNOWN
po//cs.po: UNKNOWN
po//de.po: *No copyright* GENERATED FILE
po//el.po: *No copyright* GENERATED FILE
po//es.po: *No copyright* GENERATED FILE
po//fi.po: *No copyright* GENERATED FILE
po//fr.po: UNKNOWN
po//gd.po: UNKNOWN
po//hu.po: UNKNOWN
po//id.po: *No copyright* GENERATED FILE
po//it.po: UNKNOWN
po//nl.po: UNKNOWN
po//pl.po: *No copyright* GENERATED FILE
po//pt.po: UNKNOWN
po//pt_BR.po: *No copyright* GENERATED FILE
po//ru.po: *No copyright* GENERATED FILE
po//sl.po: UNKNOWN
po//sr.po: *No copyright* GENERATED FILE
po//sv.po: UNKNOWN
po//template.pot: *No copyright* GENERATED FILE
po//tr.po: UNKNOWN
2016-09-30 / 14:17:28 ♒♒♒  ☺  
```

Can we please have license clarification, either in respective files, or elsewhere more appropriate (COPYING file) ?

**Comment by nE0sIghT** [comment]
Project license is GPL-3+ and it's text is in LICENSE file.
GNOME Translation Project is used for translations so all translations should be covered by same license as chrome-gnome-shell.

**Comment by nE0sIghT** [comment]
@rickysarraf 
Do we need to take some actions here?

**Comment by rickysarraf** [comment]
NO. Thanks. This can be closed. If anyone has concerns, I can always point them to this report.
