### ISSUE TITLE
Uninstalling some GNOME Shell extensions does not work

### ISSUE THREAD

**Issue by aleb** [nE0sIghT/chrome-gnome-shell-mirror#16]
I use Google Chrome with the "GNOME Shell integration" browser plugin. I go to https://extensions.gnome.org/local/ and I click the round X button for the "windowNavigator" extension. It is removed from the list and there is a magenta notification at the top of the page: "You uninstalled windowNavigator.". I reload the page and it's still there.

Same happens with "Workspace Indicator" and "Hello, World!".

It did work fine uninstalling others.

**Comment by nE0sIghT** [comment]
Can you try Epiphany (GNOME Web) browser and/or Firefox with NPAPI plugin? Is it reproducible with them?

**Comment by aleb** [comment]
In Epiphany it works strange, one time it failed to detect GNOME3 and the next time it showed fine the extensions.

In Firefox nothing happens if I click the round X button.

**Comment by nE0sIghT** [comment]
So neither Epiphany nor Firefox works for you?
Please also try GNOME Tweak Tool.

**Comment by aleb** [comment]
The Remove buttons are disabled:

![screenshot from 2016-10-19 17-41-57](https://cloud.githubusercontent.com/assets/505582/19526042/61a0c73a-9623-11e6-9845-0a0fd037405e.png)

**Comment by nE0sIghT** [comment]
> The Remove buttons are disabled

That means those extensions are system. To uninstall them you must use your package manager.
Extensions package is often named gnome-shell-extensions.

[I also proposed a patch for extensions.gnome.org some time ago ](https://bugzilla.gnome.org/show_bug.cgi?id=772085) to remove uninstall button for system extensions and explicitly mark them on site.

**Comment by nE0sIghT** [comment]
I merged fix for extension.gnome.org: https://github.com/GNOME/extensions-web/commit/a18e3854e7a556be868a6330c7a9385e66527d5e

It will be deployed soon.

**Comment by nE0sIghT** [comment]
Deployed several days ago
