### ISSUE TITLE
Google Chrome and Opera are not supported in Debian package

### ISSUE THREAD

**Issue by andyholmes** [nE0sIghT/chrome-gnome-shell-mirror#17]
I have chrome-gnome-shell 7.1-1 installed, as well as the Google Chrome extension but still get "native host connector not detected errors. I've uninstalled and reinstalled both with no success. I get the error both via a pop-up and on the extension website, even if I run chrome-gnome-shell in a terminal.

Any advice?

**Comment by nE0sIghT** [comment]
Which OS do you use?
How did you installed native connector - via distro package or manually?
Which browser do you use - Chrome or Chromium?

**Comment by andyholmes** [comment]
I'm using Ubuntu Gnome 16.10, installed the native connector via apt (I believe the standard repositories have a newer version than your place, but I do have it enabled) and I'm using Chrome. My Gnome shell version is 3.22.

**Comment by nE0sIghT** [comment]
You should fill a new bug against [Ubuntu 16.10 chrome-gnome-shell package](https://launchpad.net/ubuntu/+source/chrome-gnome-shell/7.1-1) - I'm not maintaining it.

For some reason @rickysarraf decided to drop Chrome support in Debian package (debian-distribution.patch).

As a workaround you can copy all .json files from `/etc/chromium/native-messaging-hosts` to `/etc/opt/chrome/native-messaging-hosts`

**Comment by rickysarraf** [comment]
Ideally, Chrome should have looked out for Chromium settings and used them. I dropped it because it meant shipping files to a location not owned by any other package, within the set of Debian's free packages.

**Comment by nE0sIghT** [comment]
> Chrome should have looked out for Chromium settings and used them

Native messaging manifests location is well documented [by Google](https://developer.chrome.com/extensions/nativeMessaging#native-messaging-host-location) and [by Opera](https://dev.opera.com/extensions/message-passing/#native-messaging-host). That is why I do not see any reason why we may ask them to change things just because we want it.

The fact is that Opera and Chrome users are broken in Debian (and technically in Ubuntu 16.10 since PPA version is lower than Universe one).
On the other hand as Debian maintainer you may not care about software that is not supported by Debian (Chrome and Opera).

So if you will not change Debian package I will only document this behavior in Wiki with workaround and link to this issue.
Definitely I will not "play" with PPA versions, so Ubuntu 16.10 users should resolve this issue together with Ubuntu GNOME maintainers.

**Comment by rickysarraf** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

On Mon, 2016-10-31 at 08:41 -0700, Yuri Konotopov wrote:
> The fact is that Opera and Chrome users are broken in Debian (and technically
> in Ubuntu 16.10 since PPA version is lower than Universe one).
> On the other hand as Debian maintainer you may not care about software that is
> not supported by Debian (Chrome and Opera).

The best in this case would be to document it on the wiki.

I could consider adding that path. But then, that'd violate FHS, as per which,
/opt is reserved for 3rd Party. 

But more than that, adding such exceptions would have no end point. Tomorrow, an
 opera user may have a similar request. So could other tools, that use the
chromium project.

- -- 
Ritesh Raj Sarraf
RESEARCHUT - http://www.researchut.com
"Necessity is the mother of invention."
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJYF446AAoJEKY6WKPy4XVpGboQAIAIcHj0f9OCk8O8rYBYue3K
nnVsTE3PtVn9BkeB2snDKb6/Iu4HVMJGEHUVr8Y8IAEqVbrXVs5SIvkPZEEk/UMN
WN6Ds1SPVKAPH/u7RUflQxbmI4kNJ6zqH99UYss7Po7cQz+ao2gqdIb2DYdfF7sA
3LAj8R/wBDvAu5zrQtBON0PFkH5SSuuRXyzKmyidTF6a8aXmAY4NbUGRuX2rgU9P
ex3FUV4faY2mwpB3n2erLLwhLYrmAVu9zGRMmZ8PLhMlASmo7cPgx/lkKMBvGvgl
RNxpkJhjr1xRMTmkCg2H+Ao/BlQOW1F8BBmUMJbV4lJmmwhOjFnVx9SQVCJrgBRX
DGTzZEBhQr0kBHNTSKFCUKjUJebEmvfmFyNhcgO+hyF2kPrWV6m+mYO0iU3lRWBI
Z57ipRlMb2AaGwB9AMSnG0z1NksBs0QPXMQTSB2InKqqIdsu3o4+7yCWzuDKtEBN
DDwPs7jjCjjo76OklIetQvnVy1THrd8W6Yos7EWeHUPtbJ/Q8zrbYutVVsM3wqrm
PXZNUxQITfLoi0Zq0482awjE9VScZuhBhT7P9CpQQhLj6wV6qyzKdsFDpk8VTp7k
PsgpmyAm3Uq83GYyJWmUfihtxGQuxI59MkYBPinl+uALJyMqfts68ESGcEqyjc8W
c5+ERazND4dKi13sK4JR
=LFUO
-----END PGP SIGNATURE-----

**Comment by nE0sIghT** [comment]
I added information to the [Installation guide](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation).

> I could consider adding that path. But then, that'd violate FHS, as per which,
/opt is reserved for 3rd Party.

AFAIK there is no FHS violation.
[As per FHS](http://www.pathname.com/fhs/pub/fhs-2.3.html#ETCOPTCONFIGURATIONFILESFOROPT): "/etc/opt: Configuration files for /opt. Host-specific configuration files for add-on application software packages must be installed within the directory /etc/opt/<subdir>, where <subdir> is the name of the subtree in /opt where the static data from that package is stored.".

chrome-gnome-shell package just provides configuration files for Google Chrome. I do not see any violations here.

**Comment by rickysarraf** [comment]
@nE0sIghT The way I interpret the language is that /opt is reserved for 3rd party and /etc/opt/ is reserved for 3rd party configuration files.

I enabled the exception to test locally, and the sanity tools also complain the same. I don't mind changing it, but I just want it to adhere to currently defined policies.

```
E: chrome-gnome-shell: dir-or-file-in-etc-opt etc/opt/chrome/
N: 
N:    Debian packages should not install into /etc/opt, because it is reserved
N:    for add-on software.
N:    
N:    Refer to Filesystem Hierarchy Standard (/opt : Add-on application
N:    software packages) for details.
N:    
N:    Severity: serious, Certainty: certain
N:    
N:    Check: files, Type: binary, udeb
N: 
E: chrome-gnome-shell: dir-or-file-in-etc-opt etc/opt/chrome/native-messaging-hosts/
E: chrome-gnome-shell: dir-or-file-in-etc-opt etc/opt/chrome/native-messaging-hosts/io.github.ne0sight.gs_chrome_connector.json
E: chrome-gnome-shell: dir-or-file-in-etc-opt ... use --no-tag-display-limit to see all (or pipe to a file/program)
```

**Comment by nE0sIghT** [comment]
@rickysarraf 

I see that this is enforced Debian (lintian) policy and there is nothing can be done to override it.
Thanks for info.

Here is similar unresolved issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=393623

Closing this then.

**Comment by nE0sIghT** [comment]
Since there is [Debian bug 840235](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840235) exists I reopening this issue to track bug 840235 status.
As I understand this is only blocker for reenabling /etc/opt configuration files in Debian.

**Comment by jbicha** [comment]
Since Ubuntu does not auto-reject packages for this lintian error, I fixed this issue in Ubuntu 17.04 Alpha and I started the process to fix Ubuntu 16.10 also. See LP [bug 1644370](https://launchpad.net/bugs/1644370)

**Comment by nE0sIghT** [comment]
@jbicha 
Thanks for info. I will update wiki page as soon as 16.04 Ubuntu package will be updated

**Comment by jbicha** [comment]
@nE0sIghT [chrome-gnome-shell](https://launchpad.net/ubuntu/+source/chrome-gnome-shell) now supports Chrome on Ubuntu 16.10 and higher once the user has applied all updates.

This is because Ubuntu does not block uploads for this particular lintian error.

**Comment by nE0sIghT** [comment]
@jbicha 

Thanks. Wiki updated

**Comment by DavidZemon** [comment]
Is a reboot necessary for this to take effect? I just found out about this (running 16.10) but it's not working. I've restarted Chrome a couple times, ensure the chrome-gnome-shell package is installed, ensured the Chrome plugin is installed... all to no avail. The extensions.gnome.org page shows the warning:

> Although GNOME Shell integration extension is running, native host connector is not detected. Refer documentation for instructions about installing connector.

**Comment by nE0sIghT** [comment]
@DavidZemon 

You have another issue since you are using Ubuntu. It is not affected.

1. Create new issue.
2. Edit ```/usr/bin/chrome-gnome-shell``` file as root user and change ```DEBUG_ENABLED = False``` to ```DEBUG_ENABLED = True```.
3. Run Chrome from command line, go to https://extensions.gnome.org and post Chrome output in new issue.

**Comment by jbicha** [comment]
@nE0sIghT By the way, chrome-gnome-shell 8 is now available in all supported Ubuntu releases 14.04+ without a PPA. It's a dependency of the Ubuntu GNOME metapackage so it will be installed already for most people. (Arguably, it might make more sense for gnome-shell to depend on it since not everyone has `ubuntu-gnome-desktop` installed.)

https://launchpad.net/ubuntu/+source/chrome-gnome-shell

**Comment by jbicha** [comment]
That doesn't mean you have to discontinue your PPA. As long as version 8 works, it probably won't be updated in stable releases.

**Comment by nE0sIghT** [comment]
@jbicha 

Thanks for your work.
I already removed PPA reference from wiki yesterday and not decided yet if I continue to provide PPA (it's consuming worktime, but I'm Gentoo user primary :-) ).

**Comment by DavidZemon** [comment]
New ticket opened as #44

**Comment by LaurentDumont** [comment]
Looks like the most recent version of Chrome does not create a `/etc/opt/chrome/native-messaging-hosts` folder. Creating it manually with `sudo mkdir -p /etc/opt/chrome/native-messaging-hosts` and moving the file from `/etc/chromium/native-messaging-hosts/org.gnome.chrome_gnome_shell.json` works just fine.

**Comment by nE0sIghT** [comment]
Finally fixed in Debian.
https://tracker.debian.org/news/902623
