### ISSUE TITLE
Can not disable update check

### ISSUE THREAD

**Issue by nE0sIghT** [nE0sIghT/chrome-gnome-shell-mirror#18]
https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/8#issuecomment-262182976

**Comment by nE0sIghT** [comment]
@madorian

> I have to remove it totally using apt 

Yes

> Also, why is this issue closed?

I created new ticket for you because your first issue is resolved. Please write here

**Comment by nE0sIghT** [comment]
@madorian

1. Open Extensions page (chrome://extensions) page
2. Enable "Developer mode"
3. Click to "extension.html" near "Inspect views"
![selection_026](https://cloud.githubusercontent.com/assets/3389586/21103979/23c54fbc-c09e-11e6-93a2-f6b74cb54beb.png)
4. Select "Console" tab
5. Run 3 statements:
```
chrome.alarms.getAll(function(response) { console.log(response); });
chrome.storage.local.get(function(response) { console.log(response); });
chrome.storage.sync.get(function(response) { console.log(response); });
```
![selection_028](https://cloud.githubusercontent.com/assets/3389586/21103980/23c6b208-c09e-11e6-8953-b6fb88d99c28.png)

6. Open results of every query by clicking to triangles.
7. Post results here.

**Comment by nE0sIghT** [comment]
@madorian ping

**Comment by madorian** [comment]
The output is like 100s' of pages long. Is there any way to capture it all?

**Comment by nE0sIghT** [comment]
@madorian 

Right mouse button -> Save as

**Comment by madorian** [comment]
That's not what I meant;)

You told me to: 

Open results of every query by clicking to triangles.

There are literally hundreds of triangles, like 300. Is there anyway to expand all?

**Comment by nE0sIghT** [comment]
Don't open them. Just save all to file and attach here

**Comment by madorian** [comment]
﻿
chrome.alarms.getAll(function(response) { console.log(response); });
chrome.storage.local.get(function(response) { console.log(response); });
chrome.storage.sync.get(function(response) { console.log(response); });
undefined
VM97:1 
[]
VM97:2 
Object
lastUpdateCheck
:
"21.11.2016, 21.21.25"
notifications
:
Object
syncExtensions
:
false
__proto__
:
Object
__defineGetter__
:
__defineGetter__()
arguments
:
null
caller
:
null
length
:
2
name
:
"__defineGetter__"
__proto__
:
()
__defineSetter__
:
__defineSetter__()
__lookupGetter__
:
__lookupGetter__()
__lookupSetter__
:
__lookupSetter__()
constructor
:
Object()
hasOwnProperty
:
hasOwnProperty()
isPrototypeOf
:
isPrototypeOf()
propertyIsEnumerable
:
propertyIsEnumerable()
toLocaleString
:
toLocaleString()
toString
:
toString()
valueOf
:
valueOf()
get __proto__
:
__proto__()
set __proto__
:
__proto__()
VM97:3 
Object
showReleaseNotes
:
false
updateCheck
:
false
updateCheckPeriod
:
6
__proto__
:
Object

**Comment by madorian** [comment]
[gphhapmejobijbbhgpjhcjognlahblep-1483471340943.txt](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/files/683051/gphhapmejobijbbhgpjhcjognlahblep-1483471340943.txt)

**Comment by nE0sIghT** [comment]
Open triangle near "notifications: object" and post screenshot here

**Comment by nE0sIghT** [comment]
This is do not needed. Thanks for attachment

**Comment by madorian** [comment]
![utvalg_020](https://cloud.githubusercontent.com/assets/10106206/21620383/5fca9168-d1f4-11e6-814d-ab5ec8cadf60.png)

**Comment by nE0sIghT** [comment]
I was wrong, this is needed. Please make screenshot of notifications object value

**Comment by nE0sIghT** [comment]
As I see, there are no alarms and saved notifications. You have update check switched off and last update check was done at Nov, 21.
You should not receive any notifications from extension.

**Comment by madorian** [comment]
and yet, I receive notifications all day long

**Comment by nE0sIghT** [comment]
Do you have any other extensions installed? Please post your extensions Chrome page.

**Comment by madorian** [comment]
![arbeidsomrade 1_022](https://cloud.githubusercontent.com/assets/10106206/21624992/da0a1006-d209-11e6-9493-f6b5146bf384.png)

This is what it displays now

**Comment by madorian** [comment]
it's displaying for other extensions, somehow

**Comment by nE0sIghT** [comment]
Open chrome://extensions/ page and post screenshot of all installed Chrome extensions

**Comment by madorian** [comment]
"name": "Actions for Gmail™ (beta)",
   "name": "AddThis - Share & Bookmark (new)",
   "name": "AirDroid",
   "name": "Always Autocomplete",
   "name": "Asana Extension for Chrome",
   "name": "Astonishing Comic Reader",
   "name": "Auto Copy",
   "name": "Autofill",
   "name": "AutoRemote",
   "name": "Auto Replay for YouTube™",
   "name": "Ballloon for Chrome",
   "name": "Better YouTube Watch History",
   "name": "BIODIGITAL HUMAN",
   "name": "Boards for Trello",
   "name": "Break Reminder",
   "name": "ChromEmacs",
   "name": "Chrome Media Router",
   "name": "CloudConvert",
   "name": "Context Menu Search",
   "name": "CookiesOK",
   "name": "CouchPotato",
   "name": "CSS Reloader",
   "name": "Don't Fuck With Paste",
   "name": "drumbit",
   "name": "Easy Put.io",
   "name": "EditThisCookie",
   "name": "Edit with Emacs",
   "name": "Email this page (by Google)",
   "name": "Emby",
   "name": "Facebook Video Downloader",
   "name": "feedly",
   "name": "Flash Video Downloader",
   "name": "GIMP on rollApp",
   "name": "Hide My Ass! Web Proxy",
   "name": "ibVPN - Best VPN & Proxy",
"name": "Journey (Diary, Journal)",
   "name": "Kami - PDF and Document Markup",
   "name": "LastPass: Free Password Manager",
   "name": "Mailto: for Gmail™",
   "name": "Mini Mammoth",
   "name": "Music Player for Google Drive",
   "name": "NavigUp",
   "name": "Offcloud",
   "name": "Offcloud for Chrome",
   "name": "OneDrive",
   "name": "Open Frame",
   "name": "Penzu",
   "name": "Pixlr Editor",
   "name": "Print and Save to the cloud with CleanSave ",
   "name": "Print Friendly & PDF",
   "name": "Pushbullet",
   "name": "QuickJump",
   "name": "Quick Search for Google Drive™",
   "name": "Read Mode",
   "name": "Reddit Enhancement Suite",
   "name": "Reddit New Comments Highlighter",
   "name": "Remote Torrent Adder",
   "name": "RT News",
   "name": "SABconnect++",
      "name": "Save this page with CleanSave"
   "name": "Save to Pocket",
   "name": "Screencastify (Screen Video Recorder)",
   "name": "scrible Toolbar",
   "name": "Select & translate - context menu",
   "name": "Send from Gmail (by Google)",
   "name": "Session Buddy",
 "name": "Show Frame",
   "name": "SmoothScroll",
   "name": "TabCloud",
   "name": "Table Capture",
   "name": "Tabs Outliner",
   "name": "TabsPlus",
   "name": "Tab Title Tweaker",
   "name": "thinkery",
   "name": "Todoist for Gmail",
   "name": ".torrent to Transmission",
   "name": "UJAM - Make your music.",
   "name": "Upload Photos to Cloudinary",
   "name": "User-Agent Switcher for Chrome",
   "name": "World Clocks",
   "name": "Wunderlist for Chrome",
   "name": "YouTweak for YouTube™ - Subscription Manager",
   "name": "Zoho Docs",

**Comment by nE0sIghT** [comment]
Thanks, I will check compatibility with this extensions.

Which version of GNOME Shell integration for Chrome do you use? Which Linux distro do you use?

**Comment by madorian** [comment]
Ubuntu-16.10, 
ii  chrome-gnome-shell                                    7.2-0ubuntu1                    all                             GNOME Shell integration for Google Chrome browser

**Comment by nE0sIghT** [comment]
Do you use Chrome or Chromium? Which version? How did you installed it?

**Comment by madorian** [comment]
Chrome 55.0.2883.87 (64-bit) I don't remember if I fetched the tarball from Chrome or just via apt.

**Comment by nE0sIghT** [comment]
Are you rebooting your PC?

**Comment by madorian** [comment]
last reboot was yesterday and I've had many reboots since this started occuring.

**Comment by nE0sIghT** [comment]
With latest version 8 result is same?

**Comment by madorian** [comment]
don't know yet, but I got the following error when I just installed it
![arbeidsomrade 1_013](https://cloud.githubusercontent.com/assets/10106206/21734779/873a904a-d465-11e6-8a8e-ce22e1763b89.png)

**Comment by nE0sIghT** [comment]
Try to reboot or restart/reload dbus

**Comment by nE0sIghT** [comment]
Could you try to create new Chromium profile, install only GNOME Shell integration extension and reproduce this problem?

**Comment by nE0sIghT** [comment]
If it's still issue for you, then provide requested information and reopen this.
