### ISSUE TITLE
debugging integration issues

### ISSUE THREAD

**Issue by rickysarraf** [nE0sIghT/chrome-gnome-shell-mirror#19]
![image](https://cloud.githubusercontent.com/assets/65480/20794321/b758767e-b7f1-11e6-9fbf-c0058abe8bfa.png)

@nE0sIghT How would you advice on debugging something like this ? I'm not sure if the issue is with Chromium browser or the chrome-gnome-shell plugin.

But lately, I'm not sure when this happened, the installed plugins do not show up. I think things may be fine on the GNOME side, because I'm able to access the plugins through Firefox.

**Comment by nE0sIghT** [comment]
Looks like requirejs timeout.
You can see timeout message in Developer Tools (F12) Console. Some time ago I increased it to [15 seconds](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/blob/master/extension/include/sweettooth-api.js#L186).

Is this constantly reproducible or happens from time to time?

**Comment by rickysarraf** [comment]
Thanks Yuri. Please find screen shot

![image](https://cloud.githubusercontent.com/assets/65480/20800959/511fcbd4-b80d-11e6-83f3-424d72f255b1.png)


```
dbus.js:78 Uncaught TypeError: Cannot read property 'then' of undefined(anonymous function) @ dbus.js:78fire @ jquery.js:1075add @ jquery.js:1110ready @ jquery.js:279exports.load @ dbus.js:41(anonymous function) @ require.js:1135(anonymous function) @ require.js:119on @ require.js:496callPlugin @ require.js:1052fetch @ require.js:920check @ require.js:959enable @ require.js:1174(anonymous function) @ require.js:1082(anonymous function) @ require.js:119(anonymous function) @ require.js:1187each @ require.js:56emit @ require.js:1186check @ require.js:1040enable @ require.js:1174init @ require.js:877callGetModule @ require.js:1199completeLoad @ require.js:1496onScriptLoad @ require.js:1641
require.js:175 Uncaught Error: Load timeout for modules: dbus!__unnormalized3,dbus!__unnormalized4,dbus!_
http://requirejs.org/docs/errors.html#timeoutmakeError @ require.js:175checkLoaded @ require.js:746(anonymous function) @ require.js:789
```

**Comment by rickysarraf** [comment]
The issue is constantly seen, since last couple weeks.

**Comment by nE0sIghT** [comment]
@rickysarraf 
Recently we upgraded e.g.o. site. With this upgrade I made backward incompatible change.
Currently, e.g.o. site is only compatible with chrome-gnome-shell browser extension 7.2.

Please upgrade browser extension : https://chrome.google.com/webstore/detail/gnome-shell-integration/gphhapmejobijbbhgpjhcjognlahblep?hl=ru
Connector version 7.1 is supported.

**Comment by nE0sIghT** [comment]
Here are relevant commits: [chrome-gnome-shell](https://git.gnome.org/browse/chrome-gnome-shell/commit/?id=6425fdf4aab71392ccc7cb1619b1fe903bf4a1e7) and [extensions-web](https://git.gnome.org/browse/extensions-web/commit/?id=9d6f222d2638088b7df60a2b6dabae8358633177)

**Comment by rickysarraf** [comment]
Yes. That worked. But I wonder why Chrom did not upgrade the extension, sensing a newer version in the Store. I had to uninstall 7.1 and then install 7.2.

I'm going to package 7.2. Wish Github had a notification feature for new releases.

**Comment by rickysarraf** [comment]
Oh!! There are no releases out here on github. Do you have a mailing list I could subscribe to ?

**Comment by nE0sIghT** [comment]
You can use [Github's feed ](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/releases.atom)or [GNOME's ftp-releases ml](https://mail.gnome.org/mailman/listinfo/ftp-release-list)

**Comment by rickysarraf** [comment]
Thanks. This issue can be closed now.
