### ISSUE TITLE
Extension should be more descritive on why the connection failed

### ISSUE THREAD

**Issue by josephgbr** [nE0sIghT/chrome-gnome-shell-mirror#2]
Currently, the Chrome extension shows only "error" when conection failed. It would be nice to have a notification with a better level of information on the error. (e.g. Reason: HTTP Error 407 Proxy Authentication Required).

**Comment by nE0sIghT** [comment]
I don't think it's possible to catch exact reason of network (non HTTP) error in Chrome.
What I can do is specify more useful (but still generic) message like "Network error occured. Please check your Internet connection or proxy settings".
