### ISSUE TITLE
"Native host has exited."

### ISSUE THREAD

**Issue by mishugashu** [nE0sIghT/chrome-gnome-shell-mirror#20]
For a couple weeks now, I haven't been able to use this extension on any of my computers. The popup for the extension just has "Native host has exited." and it pops up every time it's supposed to update. Going to the options page has this same phrase listed in red. I'm not sure what other debug information I can give you. Please let me know.

I install this application from Arch's AUR PKGBUILD here: https://aur.archlinux.org/packages/chrome-gnome-shell-git

**Comment by nE0sIghT** [comment]
Hi,

Run Chrome from command line. Hi to e.g.o. to try this error.
Then post here console output.

**Comment by mishugashu** [comment]
Seems to be something with my python environment.

```
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 15, in <module>
    from gi.repository import GLib, Gio
  File "/home/mishugashu/.pyenv/versions/3.5.2/lib/python3.5/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```

I remember mucking with reinstalling this module around the same time the error popped up. Looks like it wants it to be python2, and it definitely isn't.

**Comment by mishugashu** [comment]
Closing this since it seems to be an issue with my computer, not this project.

**Comment by nE0sIghT** [comment]
>  Looks like it wants it to be python2, and it definitely isn't.

chrome-gnome-shell itself supports any version of Python from 2.7 to 3.5 (distro maintainer should decide which version to use).
However I think there is something wrong with Gio python package.

Anyway if you think that there is some incompatibility of chrome-gnome-shell with newer Python version - feel free to reopen this.

**Comment by mishugashu** [comment]
Nope, I fixed it, and I'll explain in case anyone else comes looking for this.

It was an issue with pyenv (or possibly any python virtual environment). It could not see my package installed via pacman (python-gobject), since it is a virtual environment, so I had installed it via pip. Unfortunately, it seems their python2 code is inside the python3 pip library, so it was trying to execute python2 code with my environment, which was set at 3.5.2.

I solved the problem by symlinking my system's module directory to my virtual environment's module directory.

**Comment by gata-cerval** [comment]
@mishugashu Could you explain some more detailed what did you make to resolve the problem. I can not find what I have to change

**Comment by nE0sIghT** [comment]
@gata-cerval 

Run Chrome from command line. Go to e.g.o. to get this error.
Then post here console output.

It's better to create new issue to not bother author of this issue since it's unrelated for sure.

**Comment by gata-cerval** [comment]
@nE0sIghT 
Console output: 
> Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 20, in <module>
    import requests
ImportError: No module named requests

**Comment by nE0sIghT** [comment]
@gata-cerval

Install python-requests or python3-requests package.
Which distro are you using? How did you installed chrome-gnome-shell package?
Package maintainer forgot to add this dependency.

**Comment by gata-cerval** [comment]
@nE0sIghT  
I have had python3-requests installed but whatever got the error. 
Now I have installed python-requests and it seems chrome-gnome-shell connects to the Native host successfully. But the shell unexpectedly falls down and I have got multiple windows requested to install all my extensions, one window to each extension, and when I cancel them they flow up again. 
I think it'll be good to restart my laptop. 
I am going down. 
I will write you if i get this windows again after reboot. 

Thank you very much for your help.

**Comment by nE0sIghT** [comment]
@gata-cerval 

Looks like you have extensions synchronization enabled (it's controlled in browser extension settings).
If you already have those extensions installed this can be a bug in chrome-gnome-shell browser extension.

In any case please create new issue.

**Comment by Wkee** [comment]
Same situation for me and I wonder how can I uninstall it for re-installing it? Will it works? I don't know where is the problem when I just run chrome-gnome-shell in terminal and there is nothing to show. And when I open it in Chrome, oh, here it comes, "Native host has exited." So, how can I solve this issue? Thanks for your time.

**Comment by nE0sIghT** [comment]
@Wkee 

Do not post to closed issues instead open new one.

Run Chrome from command line. Go to e.g.o. to get error.
Then post console output in new issue.

**Comment by waldyd** [comment]
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 20, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 29, in <module>
    from .exceptions import InvalidURL, InvalidHeader, FileModeWarning
ImportError: cannot import name InvalidHeader
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 20, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 29, in <module>
    from .exceptions import InvalidURL, InvalidHeader, FileModeWarning
ImportError: cannot import name InvalidHeader
Traceback (most recent call last):
  File "/usr/bin/chrome-gnome-shell", line 20, in <module>
    import requests
  File "/usr/lib/python2.7/site-packages/requests/__init__.py", line 64, in <module>
    from . import utils
  File "/usr/lib/python2.7/site-packages/requests/utils.py", line 29, in <module>
    from .exceptions import InvalidURL, InvalidHeader, FileModeWarning
ImportError: cannot import name InvalidHeader

**Comment by nE0sIghT** [comment]
@waldyd 

You should properly install python-request and all it's dependencies.
Ask somewhere at your distro's support how to do it.

**Comment by waldyd** [comment]
```
$ sudo pip uninstall requests
$ sudo dnf install python-requests
```

**Comment by gengzhengtao** [comment]
may be not work
`sudo dnf install python-requests ` 
you can 
`sudo pip install requests --upgrade`

**Comment by nE0sIghT** [comment]
> sudo pip

You should not use pip as root usualy
