### ISSUE TITLE
The package doesn't gather through AUR

### ISSUE THREAD

**Issue by ElvisPresly** [nE0sIghT/chrome-gnome-shell-mirror#22]
```
Подготовка...
Сборка пакетов...

==> Загрузка PKGBUILD chrome-gnome-shell-git из AUR...
x .SRCINFO
x PKGBUILD
rafaelff commented on 2016-08-15 21:57			 
I don't think I can, at the moment. Please notice there is a plan for supporting opera in the roadmap page
https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/RoadMap

EDIT: my reply was in version 6.2; since version 7, this package works with Opera. Install the gnome shell integration extension for Opera in https://addons.opera.com

aseemraj commented on 2016-09-13 08:37			 
I have the chrome extension installed. When I try to install a gnome extension, I get this message on the top: "You are using different versions of GNOME Shell integration extension (version 7) and native host connector (version 6.2)"

Any idea how can I update? yaourt -S chrome-gnome-shell-git doesn't seem to help and the extensions that I install don't appear in the tweak tool.

Thanks!

rafaelff commented on 2016-09-13 10:08			 
@aseemraj: This package package currently provides only the native connector, while the extension can be installed from Chrome Web Store. Have you tried to rebuild this package, in order to obtain the version 7 ?

EDIT: Oh, you tried to rebuild, sorry. Please try also closing the web browser and starting it again, and let me know.

Mr_Resist0r commented on 2016-09-26 16:59			 
I'm a total noob and have just stared using arch. For some reason when I try to install this I get "Target not found". I'm using "chrome-gnome-shell-git" with "sudo pacman -S" because that's how I installed all the other packages.

Any help?

rafaelff commented on 2016-09-27 00:20			 
@Mr_ResistOr: You can only use pacman to install local packages or from official repositories. Since chrome-gnome-shell-git is in AUR Unsupported, you will need to "Download Snapshot" and build locally with makepkg, or to use AUR helpers (yaourt, pacaur etc) to install packages directly from AUR.

E.g., see: https://wiki.archlinux.org/index.php/Arch_User_Repository

chrome-gnome-shell-git 7.2.r12.gfa44ccd-1  (2016-11-21 13:28)
( Неподдерживаемый пакет: Потенциально опасен ! )
==> зависимости chrome-gnome-shell-git:
 - gnome-shell (уже установлен)
 - python-requests (уже установлен)
 - git (уже установлен) [makedepend]
 - cmake (уже установлен) [makedepend]


==> Продолжить сборку chrome-gnome-shell-git ? Да/нет [Y/n]
==> -------------------------------------------------------
==> 
==> Сборка и установка пакета
==> Сборка пакета chrome-gnome-shell-git 7.2.r12.gfa44ccd-1 (Вт дек 27 00:01:34 MSK 2016)
==> Проверка зависимостей для запуска...
==> Проверка зависимостей для сборки...
==> Получение исходных файлов...
  -> Клонирование репозитория 'chrome-gnome-shell' (git)...
Клонирование в голый репозиторий «/tmp/yaourt-tmp-user/aur-chrome-gnome-shell-git/chrome-gnome-shell»…
remote: Counting objects: 2423, done.
remote: Compressing objects: 100% (1871/1871), done.
remote: Total 2423 (delta 1631), reused 628 (delta 407)
Получение объектов: 100% (2423/2423), 519.91 KiB | 162.00 KiB/s, готово.
Определение изменений: 100% (1631/1631), готово.
==> Проверка файлов source с использованием md5sums...
    chrome-gnome-shell ... Пропущено
==> Распаковка исходных файлов...
  -> Создание рабочей копии репозитория 'chrome-gnome-shell' (git)...
Клонирование в «chrome-gnome-shell»…
готово.
==> Запускается prepare()...
==> Запускается pkgver()...
==> Обновлённая версия: 'chrome-gnome-shell-git 7.2.r58.gde109de-1'
==> Запускается build()...
-- Found base64: /usr/bin/base64
-- Found sha256sum: /usr/bin/sha256sum
-- Found head: /usr/bin/head
-- Found tr: /usr/bin/tr
CMake Error at CMakeLists.txt:66 (message):
  Could NOT find jq.
Call Stack (most recent call first):
  CMakeLists.txt:95 (find_program_ex)


-- Configuring incomplete, errors occurred!
See also "/tmp/yaourt-tmp-user/aur-chrome-gnome-shell-git/src/chrome-gnome-shell/build/CMakeFiles/CMakeOutput.log".
==> ОШИБКА: Произошел сбой в build().
    Прерывание...
==> ОШИБКА: Makepkg не смог собрать chrome-gnome-shell-git.
==> Перезапустить сборку chrome-gnome-shell-git ? да/Нет [y/N]
==> ----------------------------------------------------------
==> 

```

**Comment by ElvisPresly** [comment]
See also "/tmp/yaourt-tmp-user/aur-chrome-gnome-shell-git/src/chrome-gnome-shell/build/CMakeFiles/CMakeOutput.log".

`The system is: Linux - 4.8.13-1-ARCH - x86_64`

**Comment by nE0sIghT** [comment]
You should ask Arch Linux package maintainer here: https://aur.archlinux.org/packages/chrome-gnome-shell-git/

@josephgbr
https://stedolan.github.io/jq/ is a new build-time dependency. Package [exists in Arch](https://www.archlinux.org/packages/community/x86_64/jq/) as I see

**Comment by ElvisPresly** [comment]
@nE0sIghT Установил пакет jq и о чудо, пошло дальше, но снова ошибка в сборке уже другая

`=> Продолжить установку chrome-gnome-shell-git ? Да/нет [Y/n]
==> [v]просмотреть содержимое пакета [c]проверить пакет при помощи namcap
==> ---------------------------------------------------------------------
==> 
[sudo] пароль для user: 
загрузка пакетов...
разрешение зависимостей...
проверка конфликтов...

Пакеты (1) chrome-gnome-shell-git-7.2.r59.g73a1997-1

Будет установлено:  0,03 MiB

:: Приступить к установке? [Y/n] 
(1/1) проверка ключей                                 [############################] 100%
(1/1) проверяется целостность пакета                  [############################] 100%
(1/1) загрузка файлов пакетов                         [############################] 100%
(1/1) проверка конфликтов файлов                      [############################] 100%
ошибка: не удалось завершить транзакцию (конфликтующие файлы)
chrome-gnome-shell-git: '/usr/lib64' существует в файловой системе
Обнаружены ошибки, пакеты не обновлены.
==> ВНИМАНИЕ: Ваши пакеты сохранены в /tmp/yaourt-tmp-user

`

**Comment by nE0sIghT** [comment]
@ElvisPresly
Я не могу помочь с пакетом для Arch Linux (этим занимается сопровождающий пакета Arch Linux).
Это, очевидно, проблема с PKGBUILD, спроси здесь: https://aur.archlinux.org/packages/chrome-gnome-shell-git/
Сейчас католическое Рождество, вполне возможно, что человек в отпуске.

**Comment by ElvisPresly** [comment]
@nE0sIghT Спасибо за поддержку, там уже появились сотвествующий комент

mdemierre commented on 2016-12-26 22:39
The build fails for me. The following changes fixed the problem:

- Add 'jq' to dependencies
- Add -DCMAKE_INSTALL_LIBDIR='/usr/lib' in build()

Here is an updated PKGBUILD:
https://gist.github.com/mdemierre/b2cddd2b262207fb5ab14778d01cce7d

**Comment by nE0sIghT** [comment]
@ElvisPresly 
Я думаю Rafael скоро все исправит.
Проблема в том, что Arch использует git версию приложения, а новые зависимости появились буквально 2 дня назад в master ветке.

**Comment by ElvisPresly** [comment]
@nE0sIghT Не удачный я просто момент выбрал для устанвки пакета, но в любом случае, я его установил только что. Блягодаря тебе и тому человеку с комментарием в Аур

**Comment by josephgbr** [comment]
PKGBUILD fixed.

**Comment by nE0sIghT** [comment]
@josephgbr 

Thanks. Closing then

**Comment by ElvisPresly** [comment]
@nE0sIghT поставил все работает, но не пойму, нативных гномовских уведомлений нет как в Firefox?

**Comment by josephgbr** [comment]
Please notice that by updating to latest native connector host, Firefox addon seems to work, however Chromium extension complains with the following message:

> Although GNOME Shell integration extension is running, native host connector is not detected. Refer <a href='https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation'>documentation</a> for instructions about installing connector.

**Comment by nE0sIghT** [comment]
@josephgbr 
You should upgrade extension from Chrome Store to version 7.2.1

**Comment by nE0sIghT** [comment]
@ElvisPresly 
Будут в следующей версии.
Сейчас во всех браузерах используются возможности браузера по выводу уведомлений.
В следующей версии все уведомления буду выводиться через коннектор с использованием GNotification.
