### ISSUE TITLE
Copr repository Fedora 25 build

### ISSUE THREAD

**Issue by lig** [nE0sIghT/chrome-gnome-shell-mirror#23]
There is no Fedora 25 build on Copr. See https://copr.fedorainfracloud.org/coprs/region51/chrome-gnome-shell/

**Comment by nE0sIghT** [comment]
You should report this to Copr maintainer - @region51
There is contact email at the Copr page

**Comment by hmaarrfk** [comment]
https://copr.fedorainfracloud.org/coprs/hmaarrfk/chrome-gnome-shell/

**Comment by nE0sIghT** [comment]
@hmaarrfk 

Could you please provide updated spec file to [Red Hat Bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1343710)?
It's assigned, however author seems to lost interest in including package to Fedora/RHEL

**Comment by hmaarrfk** [comment]
Done. I have an issue with the 32bit build and Firefox though :S.

It seems to create a file in /usr/lib64 so strange.

**Comment by nE0sIghT** [comment]
@hmaarrfk 

Thanks. It would be nice to get chrome-gnome-shell package in main Fedora's repository.

**Comment by hmaarrfk** [comment]
Nice, yea it would be nice. Lets see if it gets accepted :D.

**Comment by nE0sIghT** [comment]
@hmaarrfk 

In Fedora Firefox is shipped in both x86 and x86_64 architectures?

**Comment by hmaarrfk** [comment]
I assume so. Firefox is the main fedora browser. 

I specified the lib directory for cmake so I think it should work for 32 bit now.

**Comment by nE0sIghT** [comment]
It seems this is fixed
