### ISSUE TITLE
Desktop configuration file should be hidden

### ISSUE THREAD

**Issue by AsavarTzeth** [nE0sIghT/chrome-gnome-shell-mirror#24]
The file connector/org.gnome.ChromeGnomeShell.desktop should probably be hidden from the user, using "NoDisplay=true". A minor thing really, but I noticed it quickly since I hide a lot of desktop files. It helps me not lose focus.

**Comment by nE0sIghT** [comment]
Thanks for the hint.
I was thinking about hiding menu entry, but missing this option while looking to Desktop file specification
