### ISSUE TITLE
[gnome-shell bug] On/Off switch sometimes not working

### ISSUE THREAD

**Issue by vsafonin** [nE0sIghT/chrome-gnome-shell-mirror#26]
Hi, I installed gnome shell integration of the store
I build from the git repository chrome-gnome-shell.
Icon appears when I log on to https://extensions.gnome.org/# there are no errors, but to establish (delete, insert) extension does not work.
No system notifications.
chromium version - 55.0.2883.75 built on Debian stretch/sid.
chrome version - 55.0.2883.87 (64-bit).

**Comment by nE0sIghT** [comment]
Do you have any GNOME extension installed (mb gnome-shell-extensions system package)?
What do you see at https://extensions.gnome.org/local/ ?
Which version of GNOME Shell do you have?

Get debug logs and pot here:
 * Edit /usr/[local/]bin/chrome-gnome-shell and change "DEBUG = False" to "DEBUG = True".
 * Open Chrome or Chromium from terminal
 * Try install/remove extension action that is not working for you
 * Post here Chrome/Chromium output (via some pastebin service if it is long)

**Comment by vsafonin** [comment]
gnome-shell-extensions - yes, it is installed, version - 3.22.2-1.
https://extensions.gnome.org/local/, see its extensions, there is no problem.
gnome-shell version - GNOME Shell 3.22.2. 

I was able to remove and install the extension, but "off" and "on" does not work
Debug:
http://pastebin.com/rZeWD0Tv

И можно по русски? мой инглишь из зе кепетал оф грейт британ...

**Comment by nE0sIghT** [comment]
Кнопки On/Off не работают на установленных расширениях?
Попробуй включить/отключить такое расширение через GNOME Tweak Tool - также не работает?
Попробуй много раз подряд быстро нажать на кнопку On/Off.

Я такую проблему наблюдаю периодически и ее корни уходят в GNOME Shell

**Comment by vsafonin** [comment]
да, кнопки  не работают, и нет уведомлений системных..
через gnome tweak tool - все хорошо, отключилось и включилось. 
Да, после большого количества раз включений и выключений - все хорошо..баг или фича? (причем работает только после того, как удалю и заного поставлю..)

Для меня более критично, на самом деле, наличие уведомлений..по крайней мере уведомление о скачивании не работает..где еще проверить пока не знаю..

**Comment by nE0sIghT** [comment]
> Да, после большого количества раз включений и выключений - все хорошо..баг или фича?

Баг. Но не в chrome-gnome-shell, а в GNOME Shell. Тот факт, что сработало в GNOME Tweak Tool - скорее всего совпадение. Я периодически наблюдаю такую ситуацию и с GNOME Tweak Tool и с NPAPI плагином - все утилиты корректно посылают DBus сообщение, но GNOME Shell не реагирует.

> уведомление о скачивании не работает

Не понимаю про какое уведомление речь.

**Comment by vsafonin** [comment]
Есть одна соц сеть, она работает исключительно через приложение (1С-коннект), у них есть веб версия, их приложение в Linux работает просто ужасно, в веб версии все более менее. 
В Firefox при получении нового сообщения, оно шлется в область уведомлений (где календарь, часы и т.д.). 
В chrome либо такого нет, либо не работает...

**Comment by nE0sIghT** [comment]
This is a bug (I believe) in GNOME Shell.
Reported as https://bugzilla.gnome.org/show_bug.cgi?id=777650

--
Russian:
Это ошибка в GNOME Shell, ссылка на багтрекер GNOME: https://bugzilla.gnome.org/show_bug.cgi?id=777650

**Comment by nE0sIghT** [comment]
Я применил обходное решение - в версии 8.1 будет работать как положено.
