### ISSUE TITLE
High CPU usage in Firefox

### ISSUE THREAD

**Issue by wsxy162** [nE0sIghT/chrome-gnome-shell-mirror#29]
Installed this extension with another one - [HTitle](https://addons.mozilla.org/zh-CN/firefox/addon/htitle/), to enable the option "Work only with GNOME Shell" in HTitle, then Firefox will take a lot CPU Usage.

But the browser works fine when these two extension separately enabled, disable "Work only with GNOME Shell" option in HTitle without disable this extension can also avoid the problem.

Since HTitle is discontinued, this coexistence issue of two extensions may not be solve. However we can easily disable the option in HTitle to workaround.

**Comment by nE0sIghT** [comment]
I think this can be a bug in Firefox.
Reported to Mozilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1337799

**Comment by nE0sIghT** [comment]
As I said in Mozilla's bugtracker - this is error in HTitle, not in GNOME Shell integration.
HTitle will break **any** browser extension, that is using native messaging.

Report this to HTitle authors.
