### ISSUE TITLE
System extensions always show (green) update icon

### ISSUE THREAD

**Issue by franglais125** [nE0sIghT/chrome-gnome-shell-mirror#31]
Hi,

I have a combination of local (~/.local/) and system (global, installed by the package manager) extensions.
When visiting https://extensions.gnome.org/local/, local extensions can be updated. But system extensions (most of them) show an update icon, when clicking this icon, the extensions is not updated (as expected), and the icon goes away. If I refresh the page, the icon appears again.

This can be confusing, as it looks like a lot of extensions have updates available, while the few extensions that **can** be updates are hard to find (as there are too many green buttons).

Thanks!
Fran

Screenshot below. In this example, "Apt Update Indicator" and "Dash to Dock" are the only *upgradable* extensions, all the others are global, and the green buttons are only cluttering the page.
![screenshot from 2017-02-09 12 13 21](https://cloud.githubusercontent.com/assets/19195975/22794465/481367a4-eec1-11e6-82a1-ab1ec176deb4.png)

**Comment by nE0sIghT** [comment]
> when clicking this icon, the extensions is not updated (as expected)

Which GNOME Shell version do you have? Those system extensions should be upgraded by installing new version to ~/.local.
When you clicking upgrade button - black overlay with install button appears?

**Comment by franglais125** [comment]
Just before the psrt you quoted, I specified that **global** extensions can't be updated, as it's expected.

The problem is that the green button still appears, even though it does nothing for **global** extensions.

It works fine for ~/.local extensions!


Gnome-shell 3.22 on Debian Stretch

**Comment by nE0sIghT** [comment]
Looks like a regression in GNOME Shell since I can update system extensions in 3.20. I will test 3.22 also.

From your screenshot I see that you are using NPAPI plugin in Firefox?

**Comment by franglais125** [comment]
I'm running Firefox, but with your extension installed. I disabled the npapu plugin. I don't have my laptop now, but I'll double check.

Thanks!

**Comment by nE0sIghT** [comment]
I just checked - it's a some bug in NPAPI plugin.
Upgrade works well with chrome-gnome-shell browser extension.

You can report this issue against GNOME Shell NPAPI plugin at https://bugzilla.gnome.org/ ot just use browser extension.

**Comment by franglais125** [comment]
Indeed! I had installed your extension, but it probably got lost in the update to Stretch.
I disabled (again) NPAPI, and everything is working fine now. Sorry for the noise!

**Comment by nE0sIghT** [comment]
As I see now, it's a bug in extensions.gnome.org site and chrome-gnome-shell wrongly handle uninstall action. Upgrade of system extensions should work with both NPAPI plugin and in chrome-gnome-shell.
I will fix this issue in website.
