### ISSUE TITLE
File closed

### ISSUE THREAD

**Issue by Zer0v87** [nE0sIghT/chrome-gnome-shell-mirror#34]
After I install the GNOME Shell Integration in Firefox I cant enable any extension on the https://extensions.gnome.org/ website. The only thing that shows up is "File closed" and a light bulb beside it. I have also installed the latest Native Host adapter manually. Help?

**Comment by nE0sIghT** [comment]
Which Firefox version do you use (how did you install it)? Which Linux distro?
How did you installed native host connector?

**Comment by Zer0v87** [comment]
I'm using version 51.0.1 and I installed it through the Ubuntu software center. My distro is Ubuntu 16.04 LTS and I followed this https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation#FreeBSD for Ubuntu to install the host adapter.

**Comment by nE0sIghT** [comment]
You are using Ubuntu 64bit?

**Comment by Zer0v87** [comment]
Yes

**Comment by nE0sIghT** [comment]
Please edit ```/usr/bin/chrome-gnome-shell``` file as root user and change ```DEBUG_ENABLED = False``` to ```DEBUG_ENABLED = True```. 
Run Firefox, go to ```Developer``` menu and choose ```Browser console```. Select only ```JS``` tab in Browser console and post here console output.

![selection_031](https://cloud.githubusercontent.com/assets/3389586/23214410/0bf8ea48-f928-11e6-8281-fcda8927b38e.png)

**Comment by Zer0v87** [comment]
I have changed the `DEBUG_ENABLED = False` to `DEBUG_ENABLED = True` as a root user. Here is the browser console output.
![tyts](https://cloud.githubusercontent.com/assets/17597577/23320758/0d4bd29c-faaa-11e6-9c1f-8644371b0d27.png)

**Comment by nE0sIghT** [comment]
Looks like it same as #35 - you do not have GNOME Shell running, but using Unity. GNOME Shell extensions will work only with GNOME Shell, not with Unity or Compiz.

Please give me screenshot of your desktop.

**Comment by Zer0v87** [comment]
![screenshot from 2017-02-24 16-54-58](https://cloud.githubusercontent.com/assets/17597577/23322692/1c4a7bbe-fab3-11e6-9c3c-8b122b1725c3.png)
Here is a screenshot of my desktop

**Comment by nE0sIghT** [comment]
It's Unity. You can not use GNOME Shel extensions and GNOME Shell integration with Unity.
If you want to use GNOME Shell extensions, then install GNOME Shell and remove Unity.

**Comment by nE0sIghT** [comment]
Reopen if you still have questions
