### ISSUE TITLE
Check for updates button

### ISSUE THREAD

**Issue by vanillajonathan** [nE0sIghT/chrome-gnome-shell-mirror#38]
It would be nice to have an easy way to check for updates.

Perhaps a "Check for updates" button inside the options, so I don't have to wait until next scheduled update check.

**Comment by nE0sIghT** [comment]
Actually, you may reset update check timer by disabling update check and re-enabling it.
There is no "Update now" button by design - I do not want to provide such feature to avoid high load for extensions.gnome.org

**Comment by vanillajonathan** [comment]
Ah, thanks.
Yes, it is not so useful.
I was just looking for such a button to click directly after installing the extension because I wanted to know if there were any updates available.

But maybe the extension does an update check when first installed?

**Comment by nE0sIghT** [comment]
> But maybe the extension does an update check when first installed?

It's not, however I think it will be a good idea to add such check

**Comment by vanillajonathan** [comment]
To communicate to the user that such a check have been done, perhaps it would be good if it logged the timestamp of the moment when the update check was performed.

This way when opening the options, it could say "Last update check &lt;date and time here&gt;".
With a time library that could be "Last update check 7 hours and 34 minutes ago".

**Comment by nE0sIghT** [comment]
It's already in options.
Last update check and next update check.

**Comment by nE0sIghT** [comment]
Update check is removed from connector in favour of GNOME Shell 3.36+ built-in functionality
