### ISSUE TITLE
Error text is rendered as text instead of HTML

### ISSUE THREAD

**Issue by vanillajonathan** [nE0sIghT/chrome-gnome-shell-mirror#39]
When the native host connector is not installed it shows the red `no_host_connector` message, but it is rendered as text not HTML which makes code for the hyperlink display instead of render as a clickable hyperlink.

**Comment by nE0sIghT** [comment]
Please provide screenshot.

**Comment by vanillajonathan** [comment]
![image](https://cloud.githubusercontent.com/assets/10222521/23718180/d0e86b9e-0436-11e7-8540-b9f6f0d697da.png)

**Comment by nE0sIghT** [comment]
Fixed in master. Thanks for report!
