### ISSUE TITLE
fedora/copr/chrome-gnome-shell

### ISSUE THREAD

**Issue by region51** [nE0sIghT/chrome-gnome-shell-mirror#4]
_Привет, если что, то я опакетил chrome-gnome-shell для F23/24/25 [link](https://copr.fedorainfracloud.org/coprs/region51/chrome-gnome-shell/)._
_P.S. ну и благодарю за chrome-gnome-shell._
:+1:

**Comment by nE0sIghT** [comment]
Привет, добавлю на днях в инструкции, спасибо

**Comment by nE0sIghT** [comment]
@region51 

Привет.
Сейчас проверял работу интеграции в GNOME 3.20 с Live окружения Fedora 24 и обнаружил, что у тебя пропущена [зависимость на pygobject3](https://developer.fedoraproject.org/tech/languages/python/pygobject.html).
Я так понимаю, что в Fedora pygobject3 - это пакет для python2, а python3-gobject - для python3.
Первый в Live окружении отсутствовал, 2ой - стоял. Но коннектор использует python2, поэтому не работает.

**Comment by region51** [comment]
@nE0sIghT привет, не проблема, добавлю https://apps.fedoraproject.org/packages/pygobject3

**Comment by region51** [comment]
слушай, наверное надо python-gobject-base, скачай пакет, пакет http://koji.fedoraproject.org/koji/buildinfo?buildID=759655 посмотри

**Comment by region51** [comment]
так как в python-gobject только _gi_cairo.so

**Comment by region51** [comment]
@nE0sIghT все проверил, нужен пакет python-gobject-base, вечером добавлю пропавшую зависимость. 

P.S. Благодарю за помощь.

**Comment by nE0sIghT** [comment]
Отлично, спасибо!
