### ISSUE TITLE
No Text on Preferences Page

### ISSUE THREAD

**Issue by AbuMaia** [nE0sIghT/chrome-gnome-shell-mirror#43]
The preferences page for this extension on Firefox 52 on Ubuntu 16.10 only has boxes and buttons, no text.

![screenshot from 2017-03-10 11-04-48](https://cloud.githubusercontent.com/assets/9308040/23808298/a100d44c-0586-11e7-95a3-62f794c162bf.png)

**Comment by nE0sIghT** [comment]
That is your locale?

**Comment by AbuMaia** [comment]
English/United States [en-us]

**Comment by nE0sIghT** [comment]
Do you using some other extensions? Which?
Could you please test with clean Firefox profile?

**Comment by nE0sIghT** [comment]
Also please open Developer Tools on options page (F12), choose Console tab and refresh page (F5).

Are there any JS errors?

**Comment by AbuMaia** [comment]
No JS errors in the Console tab. The offending extension is NoScript. About:addons is already added to the whitelist. What do I need to add to the whitelist for CGS?

**Comment by nE0sIghT** [comment]
> The offending extension is NoScript.

Options page works without NoScript?
As I see NoScript already contains required "moz-extension:" in default whitelist

**Comment by AbuMaia** [comment]
I did not have that in my whitelist. Now I do, and the extension's Preferences page is working. The Gnome extensions page, however, is now saying "Wrong extension response received".

**Comment by AbuMaia** [comment]
It took a few tries, but now it works. Had to install another extension to clear out NoScript's preferences when I uninstalled it so that a fresh set would be installed. Now it's working. Issue closed.
