### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by telmen** [nE0sIghT/chrome-gnome-shell-mirror#46]
How do I uninstall Gnome shell Integration from google chrome? It's disabled and says installed by your administrator. Help

**Comment by nE0sIghT** [comment]
How did you installed native connector?

**Comment by nE0sIghT** [comment]
Your issue is described in [wiki](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation#Troubleshooting).
If you are using Ubuntu or Debian make sure that you purge package, not just remove it.
