### ISSUE TITLE
Add extension and web-store translations to GNOME's Damned Lies

### ISSUE THREAD

**Issue by josephgbr** [nE0sIghT/chrome-gnome-shell-mirror#5]
The main benefit of adding chrome-gnome-shell to [D-L](https://l10n.gnome.org) is to reach more GNOME translators, as this project's strings will be shown in their list of modules to translate.  Also, it will ease the translator's task (as well as yours) of sending translations, as D-L has very nice built-in resource of "send to repository", which is awesome for those who don't like running Git commands.

Although D-L doesn't support json, the [Translate Toolkit](http://toolkit.translatehouse.org) provides [json2po](http://docs.translatehouse.org/projects/translate-toolkit/en/stable-1.14.0/commands/json2po.html) and [txt2po](http://docs.translatehouse.org/projects/translate-toolkit/en/stable-1.14.0/commands/txt2po.html) binaries, which could be invoked via Makefile to update all translation files, for example.

I don't know what it takes to add a project to D-L or what Makefile needs to be written (otherwise I would attach it in here), but here is my suggestion.

**Comment by nE0sIghT** [comment]
I will look into 2-way conversion using cmake

**Comment by josephgbr** [comment]
PO files looks good. Just please make sure to not lose translators's credit, which is normally placed before the first msgid -- that provide the headers of the PO file.

**Comment by josephgbr** [comment]
Oh! It seems special characters (e.g.: 'ç' in começar or 'í' in saída) got somehow weird in the json files, in the [c3c7dbc05ad43f5a7e5dad9f2cfa6c94ff1a22a6](https://git.gnome.org/browse/chrome-gnome-shell/commit/?id=c3c7dbc05ad43f5a7e5dad9f2cfa6c94ff1a22a6)

**Comment by nE0sIghT** [comment]
> Just please make sure to not lose translators's credit, which is normally placed before the first msgid

Po files will be updated by msgmerge (as part of make target) so all translator comments will be preserved as is.

> It seems special characters (e.g.: 'ç' in começar or 'í' in saída) got somehow weird in the json files

It's normal json escaping. Since this files will not be updated by hand I decided left them escaped.

It seems we done here: https://l10n.gnome.org/module/chrome-gnome-shell
