### ISSUE TITLE
Problems with synch feature.

### ISSUE THREAD

**Issue by ebola-dc** [nE0sIghT/chrome-gnome-shell-mirror#51]
My original post is at the Google Chrome webstore as Tamas Toth at 03/03/2017:
---

Dear Devs!

I love your extension as it's simply wonderful but have problem with synch feature.

On 2 computer enabled with this feature without to use one of them the extensions enabled/disabled states are randomly switch.

The exnvironment is Ubuntu Gnome 16.10 with latest dev Chrome in the background always.

Thanks for the fix in advanced if you could investigate the background.

The answer from the devs at 03/03/2017:
---

Hello, Tamás
Please create new ticket at [1] or at [2], describe your problem (and steps to reproduce) and I will try to fix those problems.

[1] https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues
[2] https://bugzilla.gnome.org/enter_bug.cgi?product=chrome-gnome-shell

And my detailed information about the problem at 03/08/2017 was the following:
---

First of all thanks for your fast response! I had no tome to answer it but will try now.

The problem is a little bit strange. When I enabled syncing at first time seems everything be ok. Later, and yet don't know the exact situation when sync feature try to do it's job the result is to forget some of my enabled extensions states. The result is totally ad-hoc. Sometimes it disable my X extension but at other sometimes it disable my Y extension. The installed state of my extensions is always correct but randomly disable some of my activly used ones.

My latest investigation is that when my device suspend and later I try to wake it up in this case in 90% of situations the sync disable some of my extensions. And the most important thing is that after login I got a warning notification about timeout of syncing. So it's seems that after a wake up procedure while my network is not alive again (as this has some delay) the sync feature try to sync but without active connection it drop it's job. After a fresh start of the device I think the problem is not available just when I try to wake up from stand-by.

Sorry for my English but hope you can understand me and can help on the problem.

Very lot of thanks for your effort!

----------

Hope you can solve the problem,

**Comment by nE0sIghT** [comment]
Hello.

This was already reported at https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/45
I was able to reproduce it and will fix this in next extension version

**Comment by ebola-dc** [comment]
Thank you!

I saw that but reported as I wrote this almost 3 weeks ago (just not me but on the store) and thought this is the correct way to log all informations on the required place.

Thanks for the support again!
