### ISSUE TITLE
Fedora 24: conflict with chrome-remote-desktop

### ISSUE THREAD

**Issue by tolgamalachi** [nE0sIghT/chrome-gnome-shell-mirror#55]
hello,

for some weeks now the website extensions.gnome.org does not work for me. for some reason i have to install the chrome-gnome-shell-mirror...well, ok.

enabled the copr and tried to install it. here is what i get (translated):  
```
Error: Transaction check error:
  File /etc/opt/chrome/native-messaging-hosts from the installation of chrome-gnome-shell-8.2.1-1.fc24.noarch collides with the file of the package chrome-remote-desktop-56.0.2924.87-3.fc24.x86_64
```

**Comment by nE0sIghT** [comment]
This is a bug in chrome-remote-desktop package. Report this to package maintainer.
See also: https://bugzilla.redhat.com/show_bug.cgi?id=1343710#c42
