### ISSUE TITLE
(unconfirmed) breaks ability to install/remove other extensions

### ISSUE THREAD

**Issue by brandonmp** [nE0sIghT/chrome-gnome-shell-mirror#56]
Had some ugly problems w/ installing Chrome extensions today, and my trouble-shooting led me to conclude that Gnome Chrome Shell was the culprit.  I can't spend the time it'd take to say conclusively that it was Gnome Chrome Shell, but I wanted to pass a note in case anyone else witnesses this behavior.

Ubuntu Gnome 17.04
Chrome  57.0.2987.133

I did a fresh install of Ubuntu Gnome 17.04 today, installed Chrome, and signed-in to the browser w/ my google account. i added the Gnome extension at some point while I was setting-up Gnome. In my previous install of Ubuntu, I hadn't used the Gnome Chrome extension.

I'm developing a chrome extension, and today the browser started freezing each time I tried to install/remove my extension from the browser, closing the browser via app menu was only solution. The same freeze happened when trying to add an extension from a `.crx` file or directly from the Chrome Webstore.

I assumed it was my ext, but the behavior repeated for every extension (incl. extensions from Google, like 'Slides'). 

To troubleshoot, I:

- used Synaptic to completely uninstall Chrome & re-installed it
- (as advised in [recent post in Google's tech support](https://productforums.google.com/forum/#!msg/chrome/iMaUFNEl70I/62AVc2DKBAAJ)) I deleted my cache/cookies 
- reset the browser settings
- tried a new profile 

None of these worked, and by this point, the only Chrome extension left was Gnome Shell (b/c it 'was installed by my administrator').  To remove it, I ran (found in the docs somewhere):

```
sudo rm /etc/chromium/policies/managed/chrome-gnome-shell.json
sudo rm /etc/opt/chrome/policies/managed/chrome-gnome-shell.json
```

Then I logged into the browser again, and extension installation worked as expected.

**Comment by nE0sIghT** [comment]
> browser started freezing each time I tried to install/remove my extension from the browser

Why you thinking it's GNOME Shell integration, but not **your** extension break your browser?
Give me link to Chrome Store to your extension

**Comment by brandonmp** [comment]
thanks for responding @nE0sIghT . at first I assumed it was [my extension](https://chrome.google.com/webstore/detail/the-wayhome-button/igempaflfbdppajmicmamiahahkihhkd) that was breaking it :) 

but once I uninstalled my extension (and all the other extensions), the problem was still there.  

Anyway I'm closing the issue. After awhile the my problem came back, and I didn't re-install any extensions at all, so something must be broken in my Chrome installation.
