### ISSUE TITLE
"no_gnome_shell" displayed at gnome shell extension website

### ISSUE THREAD

**Issue by sebastien-bugzilla** [nE0sIghT/chrome-gnome-shell-mirror#57]
Hello
I have a problem using Gnome-Shell extensions. It seems that the website does not recognize my GS version. I've a message 'no_gnome_shell' at the top of the window [1]. It seems linked to
I've read the installation manual and checked that:
- https://addons.mozilla.org/en/firefox/addon/gnome-shell-integration/ is installed and activated. [2]
- chrome-gnome-shell 8.2.1 is also installed

_sebastien@zesty:~$ apt-cache policy chrome-gnome-shell 
chrome-gnome-shell:
  Installé : 8.2.1-1ubuntu1
  Candidat : 8.2.1-1ubuntu1
 Table de version :
 *** 8.2.1-1ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu zesty/universe amd64 Packages
        500 http://archive.ubuntu.com/ubuntu zesty/universe i386 Packages
        100 /var/lib/dpkg/status_

Is there something I missed ? 
I'm using Ubuntu Zesty 17.04.

[1] : error message:
![bug_extension_gs](https://cloud.githubusercontent.com/assets/11858104/25090546/23819166-2384-11e7-93b2-383ca91ebcac.jpg)

[2] : Gnome-shell-integration is installed and activated:
![bug_extension_gs2](https://cloud.githubusercontent.com/assets/11858104/25090573/4a6f2ca2-2384-11e7-9b30-b800684da77d.jpg)

**Comment by nE0sIghT** [comment]
> I've a message 'no_gnome_shell' at the top of the window

Message is so ugly because you need extension version 9 which is on moderation by Mozilla team.

> Is there something I missed ?

I see that you have GNOME Shell installed, but it seems it is not running.
Give me full screenshot of your desktop and I can say for sure.

**Comment by sebastien-bugzilla** [comment]
Thank you for your quick answer. Yes I've GS. See a full picture below. Particularity : I use gnome3-staging ppa to have latest gnome 2.24. 


![capture d ecran de 2017-04-17 17-09-28](https://cloud.githubusercontent.com/assets/11858104/25093304/fb29bb2c-2391-11e7-848e-c564f70508be.png)

**Comment by nE0sIghT** [comment]
You are using GNOME Flashback (Metacity), not GNOME Shell.
Look [here](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/50) for similar issue.

**Comment by nE0sIghT** [comment]
Show output of ```ps -ef | grep gnome-shell```

**Comment by sebastien-bugzilla** [comment]
I don't think so. gnome-flashback is not installed:

> sebastien@zesty:~$ apt-cache policy gnome-flashback
gnome-flashback:
  Installé : (aucun)
  Candidat : 3.22.1-0ubuntu1
 Table de version :
     3.22.1-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu zesty/universe amd64 Packages

gnome shell is running:

> sebastien@zesty:~$ ps -ef | grep gnome-shell
gdm       1113  1093  1 17:26 tty1     00:00:02 /usr/bin/gnome-shell
sebasti+  1587  1396 10 17:26 tty2     00:00:17 /usr/bin/gnome-shell
sebasti+  1612  1371  0 17:26 ?        00:00:00 /usr/lib/gnome-shell/gnome-shell-calendar-server
sebasti+  3037     1 15 17:27 tty2     00:00:16 /usr/lib/firefox/firefox https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/57#issuecomment-294508322
sebasti+  3261  3037  0 17:27 tty2     00:00:00 /usr/bin/python3 /usr/bin/chrome-gnome-shell /usr/lib/mozilla/native-messaging-hosts/org.gnome.chrome_gnome_shell.json
sebasti+  3340  1371  0 17:27 ?        00:00:00 /usr/bin/python3 /usr/bin/chrome-gnome-shell --gapplication-service
sebasti+  5230  3549  0 17:29 pts/0    00:00:00 grep --color=auto gnome-shell

**Comment by sebastien-bugzilla** [comment]
More information for command line. Maybe it will help you:

> sebastien@zesty:~$ firefox https://extensions.gnome.org
1492443415897	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
1492443415904	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing externally_connectable: An unexpected property was found in the WebExtension manifest.
1492443415905	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing optional_permissions: An unexpected property was found in the WebExtension manifest.

**Comment by nE0sIghT** [comment]
@sebastien-bugzilla 

This problem was already fixed in chrome-gnome-shell version 9. However there is only affected 8.2.1 version in Ubuntu repository.
To fix it open ```/usr/bin/chrome-gnome-shell``` and change line 366 from
```
if source.lookup(SHELL_SCHEMA, False) is not None and shell_version is not None:
```
to
```
if source.lookup(SHELL_SCHEMA, True) is not None and shell_version is not None:
```

@jbicha

I think you may want to apply [this patch](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/commit/d43f0f97f5fd56dafaecd6b95b00de8cf02d5432) in Ubuntu

**Comment by sebastien-bugzilla** [comment]
Thank you ! It worked perfectly !
I close the issue.

**Comment by alexandru-serbuta** [comment]
I have the same issue. In my /usr/bin/chrome-gnome-shell, I already had line 366 set on true, so I had nothing to change.

> To fix it open /usr/bin/chrome-gnome-shell and change line 366 from
> 
> if source.lookup(SHELL_SCHEMA, False) is not None and shell_version is not None:
> 
> to
> 
> if source.lookup(SHELL_SCHEMA, True) is not None and shell_version is not None:

**Comment by nE0sIghT** [comment]
@alexandru-serbuta 
Make sure that you have GNOME Shell installed and running

**Comment by qwasinodough** [comment]
I also encounter this issue however not under my main account but under my sons account. He wants the same layout as I have. Main (root) account is 'paul'.

ruben@xxx:~$ ps -ef|grep gnome-shell
paul      2378  2082  0 18:33 ?        00:01:14 /usr/bin/gnome-shell
paul      2988  2064  0 18:33 ?        00:00:00 /usr/lib/gnome-shell/gnome-shell-calendar-server
paul      7612  7228  0 19:07 ?        00:00:00 /usr/bin/python3 /usr/bin/chrome-gnome-shell chrome-extension://gphhapmejobijbbhgpjhcjognlahblep/
ruben    17450 17257  0 20:30 ?        00:00:00 /usr/bin/python3 /usr/bin/chrome-gnome-shell /usr/lib/mozilla/native-messaging-hosts/org.gnome.chrome_gnome_shell.json chrome-gnome-shell@gnome.org
ruben    19737 19599  0 20:52 pts/1    00:00:00 grep --color=auto gnome-shell

Line 366 of /usr/bin/chrome-gnome-shell:
if source is not None and source.lookup(SHELL_SCHEMA, True) is not None and shell_version is not None:

Your suggestions are highly appreciated.
