### ISSUE TITLE
Update extension: "Cancel" button removes the extension

### ISSUE THREAD

**Issue by franglais125** [nE0sIghT/chrome-gnome-shell-mirror#59]
When updating extensions, if a user presses the "Cancel" button, th extensions is removed. I tested this on Firefox, on Gnome 3.22.

To reproduce:
1. Find an extension that needs to be updated
2. Press on the green icon to update
3. Press "Cancel"
4. Extension is removed

I'd expect the process to be cancelled, and the extension to remain in its previous state.

**Comment by nE0sIghT** [comment]
This is known GNOME Shell issue, that [was reported in 2012](https://bugzilla.gnome.org/show_bug.cgi?id=676416).
Looks like it's in "patch needed" state. I will look into imroving this process

**Comment by franglais125** [comment]
Thanks for the info! Good to know it's a known issue.

**Comment by nE0sIghT** [comment]
Closing this issue in favor of Gitlab one: https://gitlab.gnome.org/GNOME/chrome-gnome-shell/issues/7.
You may subscribe to Gitlab issue for updates.
The fix is in progress.
