### ISSUE TITLE
Проблема в хроме

### ISSUE THREAD

**Issue by gargullia** [nE0sIghT/chrome-gnome-shell-mirror#6]
![2016-06-11 21-27-08](https://cloud.githubusercontent.com/assets/19420334/16007994/3a2d5d9e-317e-11e6-801b-b05d6e941808.png)

**Comment by nE0sIghT** [comment]
В настройках включена опция "Показывать информацию о сетевых ошибках"?

**Comment by gargullia** [comment]
@nE0sIghT ошибка сыпится и когда стоит и когда нет

**Comment by nE0sIghT** [comment]
Включи опцию - должна быть написана конкретная ошибка. Сделай скриншот и
выложить сюда
17 июня 2016 г. 21:29 пользователь "gargullia" <notifications@github.com>
написал:

**Comment by nE0sIghT** [comment]
Если все еще воспроизводится - открой тикет и приложи скриншот ошибки с включенной опцией
