### ISSUE TITLE
Firefox addon's setting page  displays abnormally

### ISSUE THREAD

**Issue by Novite5** [nE0sIghT/chrome-gnome-shell-mirror#60]
My system is Ubuntu 16.04 lts 64bit,  Firefox 53.0, locale is zh-CN.
I've installed addon according to the instruction.
But the setting page displays like this:
![default](https://cloud.githubusercontent.com/assets/16817335/25706747/ec5c805e-3113-11e7-8e89-59d604ef3142.png)

**Comment by nE0sIghT** [comment]
Works fine for me in Gentoo GNU/Linux. Looks like some Ubuntu issue - report this to Ubuntu maintainers.
![selection_031](https://cloud.githubusercontent.com/assets/3389586/26137197/b3036076-3ad1-11e7-9b4c-5931ff948b81.png)

**Comment by nE0sIghT** [comment]
If you have NoScript extension installed - it's misconfigured. You should enable scripts for special pages (enabled by default).

**Comment by Novite5** [comment]
I don't use NoScript. I have tried to figure out which addon causes the problem by disabling them then enabling one by one again. Then I found it causes by OmniSidebar. When the setting page is showed in sidebar, no matter in which size, always displays like the pic above.

**Comment by nE0sIghT** [comment]
> When the setting page is showed in sidebar

This is custom OmniSidebar way to display settings. Report this to OmniSidebar authors.
