### ISSUE TITLE
firefox 53 on ubuntu 16.04 both 64 bit "an unexpected error has occured"

### ISSUE THREAD

**Issue by ajrc0re** [nE0sIghT/chrome-gnome-shell-mirror#61]
`sudo apt-get install chrome-gnome-shell
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  snap-confine
Use 'sudo apt autoremove' to remove it.
Suggested packages:
  chromium | chromium-browser
The following NEW packages will be installed:
  chrome-gnome-shell
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/12.9 kB of archives.
After this operation, 166 kB of additional disk space will be used.
Selecting previously unselected package chrome-gnome-shell.
(Reading database ... 255689 files and directories currently installed.)
Preparing to unpack .../chrome-gnome-shell_8.1-0ubuntu5_all.deb ...
Unpacking chrome-gnome-shell (8.1-0ubuntu5) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for gnome-icon-theme (3.12.0-1ubuntu3) ...
Setting up chrome-gnome-shell (8.1-0ubuntu5) ...
`
Install seems fine

An unexpected error occurred at the top of website. Uninstalling and refreshing the page shows Although GNOME Shell integration extension is running, native host connector is not detected. Refer documentation for instructions about installing connector. Reinstalling chrome-gnome-shell (sudo apt-get install chrome-gnome-shell) brings page back to showing "An unexpected error occurred"

This is a relatively fresh ubuntu install, very few changes have been made from stock. Not sure what could be the issue.

**Comment by yohanboniface** [comment]
Try to run firefox from the command line to get the stacktrace of the error and paste it here.

**Comment by nE0sIghT** [comment]
@ajrc0re 
Is it still issue?

**Comment by nE0sIghT** [comment]
Reopen if it is still issue

**Comment by GianniGi** [comment]
still the same problem in 22.04
