### ISSUE TITLE
regressions with chrome-gnome-shell 9 in Firefox

### ISSUE THREAD

**Issue by jbicha** [nE0sIghT/chrome-gnome-shell-mirror#66]
Ubuntu is attempting to update chrome-gnome-shell to 9 but it is not working with Firefox with Ubuntu [16.04 LTS](https://launchpad.net/ubuntu/+source/chrome-gnome-shell/9-0ubuntu1~ubuntu16.04.2/+build/12576498) (gnome-shell 3.18) or Ubuntu [16.10](https://launchpad.net/ubuntu/+source/chrome-gnome-shell/9-0ubuntu1~ubuntu16.10/+build/12575930) (gnome-shell 3.20). It does work in Ubuntu 17.04 (gnome-shell 3.24).

Version 8 worked fine for me on those versions (although one person did tell me that even version 8 did not work for him with Firefox on 16.04 LTS, but version 9 worked for him with Google Chrome).

"Although GNOME Shell integration extension is running, native host connector is not detected."

This bug is keeping Ubuntu from providing a version of chrome-gnome-shell that will work for all Ubuntu users with Firefox 54 which will be released to all Ubuntu users in about 2 weeks.

**Comment by nE0sIghT** [comment]
Is there deb file for 16.04 available that I can test?

**Comment by nE0sIghT** [comment]
There is error in deb package for 16.04 (I guess in 16.10 too).
File ```org.gnome.chrome_gnome_shell.json``` should be installed to ```/usr/lib[64]/mozilla/native-messaging-hosts```, but it is installed in ```/usr/lib/x86_64-linux-gnu/mozilla/native-messaging-hosts```

**Comment by jbicha** [comment]
@kenvandine Can you take care of fixing that or do you want me to? ^

@nE0sIghT Thanks for the help! I'll go ahead and close this issue now.
