### ISSUE TITLE
can't install extensions - Native host has exited error 

### ISSUE THREAD

**Issue by amirsinashadkami** [nE0sIghT/chrome-gnome-shell-mirror#67]
hi, 
i cant install gnome extensions through the chromium browser 

FYI : i already see this : "https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/50" issue and i did what was suggested but still doesn't work ! ...

**# terminal output of : chromium-browser https://extensions.gnome.org/ :** 
amirsina@Amirsina:~$ chromium-browser https://extensions.gnome.org/
[4534] Uncaught exception of type <class 'AttributeError'> occured
  File "/usr/bin/chrome-gnome-shell", line 226, in on_input
    self.process_request(request)
  File "/usr/bin/chrome-gnome-shell", line 375, in process_request
    'shellVersion': shell_version.unpack(),
[4534] Exception: 'NoneType' object has no attribute 'unpack'
[4596] Uncaught exception of type <class 'AttributeError'> occured
  File "/usr/bin/chrome-gnome-shell", line 226, in on_input
    self.process_request(request)
  File "/usr/bin/chrome-gnome-shell", line 375, in process_request
    'shellVersion': shell_version.unpack(),
[4596] Exception: 'NoneType' object has no attribute 'unpack'
[4197:4234:0601/145054.373993:ERROR:ssl_client_socket_impl.cc

P.s : im using ubuntu 16.04.2 lts

**Comment by nE0sIghT** [comment]
You do not have GNOME Shell installed or running.

**Comment by amirsinashadkami** [comment]
i have , 
I followed this structure :
https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation

**Comment by nE0sIghT** [comment]
Attach here screenshot of your desktop.

GNOME Shell integration is not GNOME Shell.
GNOME Shell integration requires GNOME Shell.

**Comment by amirsinashadkami** [comment]
![screenshot from 2017-06-01 15-39-55](https://cloud.githubusercontent.com/assets/20769213/26677545/0616537c-46bc-11e7-91cc-00e54b4e9874.png)


I followed this : http://www.omgubuntu.co.uk/2016/05/install-gnome-3-20-ubuntu-16-04-lts 
before installing GNOME Shell integration and i have gnome tweak 

![fdgv](https://cloud.githubusercontent.com/assets/20769213/26677752/bd0fd918-46bc-11e7-939a-d522a3c6eb20.png)

![ssss](https://cloud.githubusercontent.com/assets/20769213/26677728/ae1a1356-46bc-11e7-8b70-0b9e61f8f1d0.png)

I just realized i can't install gnome-shell-dbg

**Comment by nE0sIghT** [comment]
Show output of ```ps -ef | grep gnome-shell```

**Comment by amirsinashadkami** [comment]
amirsina@Amirsina:~$  ps -ef | grep gnome-shell : 

amirsina  7082  6921  0 15:40 ?        00:00:00 /usr/bin/python3 /usr/bin/chrome-gnome-shell /usr/lib/mozilla/native-messaging-hosts/org.gnome.chrome_gnome_shell.json
amirsina  9021  8943  0 16:08 pts/6    00:00:00 grep --color=auto gnome-shell

**Comment by nE0sIghT** [comment]
As I said before - you don't have **GNOME Shell** running.
Your desktop looks like Unity.

**GNOME Shell integration** doesn't work with Unity and requires that **GNOME Shell** both:
1) Installed
2) Running

**Comment by amirsinashadkami** [comment]
how can i run gnome shell  and deactivate unity

**Comment by nE0sIghT** [comment]
I do not use Ubuntu. Ask at some Ubuntu help resource.

**Comment by amirsinashadkami** [comment]
amirsina@Amirsina:~$ sudo apt-get install gnome-shell
Reading package lists... Done
Building dependency tree       
Reading state information... Done
gnome-shell is already the newest version (3.20.4-0ubuntu2~ubuntu16.04.1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
amirsina@Amirsina:~$
