### ISSUE TITLE
It's a conflict between chrome-gnome-shell and chrome-remote-desktop

### ISSUE THREAD

**Issue by moisesbites** [nE0sIghT/chrome-gnome-shell-mirror#69]
Hello,

when I tried this command:
`$ sudo dnf install -y chrome-gnome-shell chrome-remote-desktop`

There is a error message in the end:
`o arquivo /etc/opt/chrome/native-messaging-hosts da instalação de chrome-gnome-shell-9-1.fc25.noarch conflita com o arquivo do pacote chrome-remote-desktop-58.0.3029.110-2.fc25.x86_64
`
There is a conflict : the file /etc/opt/chrome/native-messaging-hosts from chrome-gnome-shell-9-1.fc25.noarch is in conflict with the file from chrome-remote-desktop-58.0.3029.110-2.fc25.x86_64

Thank you.

**Comment by nE0sIghT** [comment]
It is a bug in chrome-remote desktop package. Report this to chrome-remote-desktop package maintainer.

See also: https://bugzilla.redhat.com/show_bug.cgi?id=1343710#c42

**Comment by moisesbites** [comment]
ok. Thank you.
