### ISSUE TITLE
chrome-gnome-shell.py: use setup.py for installation

### ISSUE THREAD

**Issue by region51** [nE0sIghT/chrome-gnome-shell-mirror#7]
Есть ошибка

`chrome-gnome-shell.noarch: E: wrong-script-interpreter /usr/bin/chrome-gnome-shell /usr/bin/env python`

[maxim@localhost ~]$ rpmlint -I wrong-script-interpreter
wrong-script-interpreter:
This script uses an interpreter which is either an inappropriate one or
located in an inappropriate directory for packaged system software.

Исправишь?

**Comment by nE0sIghT** [comment]
Не совсем понимаю что исправлять.
Шебанг с марта месяца не менялся: https://github.com/nE0sIghT/chrome-gnome-shell-mirror/commit/3cf942168a96e5a3cafd0d58188fbb9fc5809ac8.

Это чья ошибка? Когда появляется?

**Comment by nE0sIghT** [comment]
Чья ошибка вижу, но не понимаю, что не так с шебангом

**Comment by region51** [comment]
В Fedora есть такая приблуда как rpmlint https://github.com/rpm-software-management/rpmlint
>Tool for checking common errors in rpm packages

ну она и ругается на это.

**Comment by nE0sIghT** [comment]
Причину, [почему rpmlint ругается нашел](http://webcache.googleusercontent.com/search?q=cache:nJ5hUbJdN9wJ:comments.gmane.org/gmane.linux.redhat.fedora.extras.packaging/10881+&cd=1&hl=ru&ct=clnk&gl=ru).
Я планировал установку коннектора перевести на setup.py - тогда твоя проблема уйдет.

Пока - сделай патч для шебанга и используй в spec файле

**Comment by nE0sIghT** [comment]
Решение - в мастер ветке. Войдет в следующую версию
