### ISSUE TITLE
Native host has exited

### ISSUE THREAD

**Issue by liufuyang** [nE0sIghT/chrome-gnome-shell-mirror#71]
* Open terminal
* If you are using Chromium then type "chromium-browser". If you are using Google Chrome then type "google-chrome"
* Go to https://extensions.gnome.org - so you will get your error message `Native host has exited`
* Copy terminal output here:
```
fuyang@fuyang-mini:~$ google-chrome
[15622:15656:0609/184656.185635:ERROR:browser_gpu_channel_host_factory.cc(103)] Failed to launch GPU process.
Created new window in existing browser session.
```
I have a motherboard Asus Z270i with an on board video card and a standalone GPU 1080Ti

**Comment by nE0sIghT** [comment]
First of all look to [this issues](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues?utf8=%E2%9C%93&q=is%3Aissue%20exited).
If all of them will not help you, then run ```chrome-gnome-shell``` from terminal and post output here.

**Comment by liufuyang** [comment]
Could not find similar issue :S 

There is no output, and when I set the debug to be true, this is what it looks like. The program just hang on there.
```
fuyang@fuyang-mini:~$ chrome-gnome-shell
[5088] Main. Use CTRL+D to quit.
```

**Comment by liufuyang** [comment]
Oh, I see. I tried to reinstall my video card driver and then it gives some different error. Then I realized that I was on Ubuntu Unity not Gnome. I guess that is the main reason? Anyway, thanks for the feed back.
