### ISSUE TITLE
Plugin is blocking Firefox's new multiprocess support

### ISSUE THREAD

**Issue by danielquinn** [nE0sIghT/chrome-gnome-shell-mirror#72]
Firefox 54 supports window multiprocessing and the speed improvement is substantial. However, plugins like this one that only support the legacy format (ie not webextensions) block this feature.

Given that Firefox 57 is slated to drop all support for legacy formats, this is probably something worth looking into.

**Comment by danielquinn** [comment]
Correction: I thought it was blocking but it turns out the problem was a different plugin that I'd thought I'd already disabled.  I'll close this now.

**Comment by nE0sIghT** [comment]
GNOME Shell integration for Chrome is not a plugin, but WebExtension which fully compatible with Firefox multiprocessor mode.
