### ISSUE TITLE
Multiprocess Firefox (e10s)

### ISSUE THREAD

**Issue by HarlemSquirrel** [nE0sIghT/chrome-gnome-shell-mirror#73]
Now that Firefox 54 is out with multiprocess enabled by default I was wondering if there are plans to support that here?

https://developer.mozilla.org/en-US/Firefox/Multiprocess_Firefox

**Update**: I think it's actually working now according to my `about:support`
![screenshot from 2017-06-21 09-15-27](https://user-images.githubusercontent.com/6445815/27385946-3756344c-5662-11e7-949a-8eebf37b887f.png)

**Comment by nE0sIghT** [comment]
It's supported from first public release.
