### ISSUE TITLE
no_gnome_shell message

### ISSUE THREAD

**Issue by MartinNdegz** [nE0sIghT/chrome-gnome-shell-mirror#74]
I am having an issue with gnome extension site.I can't get to download extensions i keep having this issue that i have no GNOME shell.
![gnome issue](https://user-images.githubusercontent.com/23105421/27515320-15f825a4-59a9-11e7-85bd-aef75dcf39a1.png)
I am thinking i have a GNOME shell since i have checked on its version.

**Comment by nE0sIghT** [comment]
Show output of ```ps -ef | grep gnome-shell```.
If it is empty, then you do not have GNOME Shell running.

**Comment by MartinNdegz** [comment]
so how do i make the GNOME shell run? Its empty i never knew that.
![gnome3](https://user-images.githubusercontent.com/23105421/27515923-71aba7fa-59b7-11e7-97ae-026566c6033e.png)

**Comment by nE0sIghT** [comment]
> so how do i make the GNOME shell run?

I not using Ubuntu and can not help with that. Try to ask at some Ubuntu forum or so.

**Comment by MartinNdegz** [comment]
i have found it in the log in section.. let me close the issue.Thanks
