### ISSUE TITLE
Failed to check extension updates

### ISSUE THREAD

**Issue by rvernica** [nE0sIghT/chrome-gnome-shell-mirror#75]
When I start Firefox, I get the following notification:

```
GNOME Shell Integration
Failed to check extensions updates: [SSL: CERTIFICATE_VE...
```

I do use a web proxy to access the Internet but that is setup in Gnome Network (Network proxy) setting. I use an Automatic proxy with a Configuration URL.

---
* chrome-gnome-shell: Version     : `9` Release     : `1.fc24`
* gnome-shell Version     : `3.20.4` Release     : `3.fc24`
* Firefox: `54.0 (64-bit)`
* Fedora: `24`

**Comment by nE0sIghT** [comment]
Proxy support is enabled in git master only.
You can try commit https://github.com/nE0sIghT/chrome-gnome-shell-mirror/commit/104d2139ad19ff067360fc64e1801a6aa2930066

**Comment by nE0sIghT** [comment]
Reopen if you still have issues.
