### ISSUE TITLE
Web Extention: native host connector is not detected.

### ISSUE THREAD

**Issue by duvjones** [nE0sIghT/chrome-gnome-shell-mirror#77]
So I am a little lost here...

I am on Fedora 26, everything is up to date, I have downloaded the Web Extension, but I keep getting this on the https://extentions.gnome.org/ site, "Although GNOME Shell integration extension is running, native host connector is not detected."
The documentation doesn't seem to cover what is happening here, would you happen to have any other ideas on what is going on or how I can fix this myself?

**Comment by nE0sIghT** [comment]
Look to:
1. https://bugzilla.redhat.com/show_bug.cgi?id=1343710
2. https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation#Fedora_Linux

Reopen if you will have some questions.
