### ISSUE TITLE
Can't launch chrome-gnome-shell on Fedora 25

### ISSUE THREAD

**Issue by SDSDOS** [nE0sIghT/chrome-gnome-shell-mirror#79]
When i was trying to install extensions from "https://extensions.gnome.org/", I was told that "Although GNOME Shell integration extension is running, native host connector is not detected", and after that I execute "sudo chrome-gnome-shell", the terminal shows: 

[5576] Uncaught exception of type <type 'exceptions.TypeError'> occured
  File "/bin/chrome-gnome-shell", line 585, in <module>
    app = ChromeGNOMEShell(run_as_service)
  File "/bin/chrome-gnome-shell", line 82, in __init__
    None)
[5576] Exception: Argument 0 does not allow None as a value

(process:5576): GLib-GIO-CRITICAL **: g_application_release: assertion 'application->priv->use_count > 0' failed

**Comment by nE0sIghT** [comment]
What chrome-gnome-shell version do you use?

**Comment by SDSDOS** [comment]
`
=========================================================================================================================================================================
 Package                                    Arch                           Version                             Repository                                           Size
=========================================================================================================================================================================
Installing:
 chrome-gnome-shell                         noarch                         9-1.fc25                            region51-chrome-gnome-shell                          33 k

Transaction Summary
=========================================================================================================================================================================
`

**Comment by nE0sIghT** [comment]
Looks like some DBus problem.
I will test chrome-gnome-shell on F25.

**Comment by nE0sIghT** [comment]
With clean Fedora 25 installation there is no errors

**Comment by nE0sIghT** [comment]
Which browser do you using?

**Comment by SDSDOS** [comment]
```
[localhost@localhost ~]$ firefox --version
Mozilla Firefox 54.0a2
```

**Comment by SDSDOS** [comment]
The problem still exists using Firefox 56.0.

**Comment by SDSDOS** [comment]
I find that the connector can be detected with the Firefox browser installed from the official Fedora repository but not with the version directly downloaded from [Mozilla Firefox](https://www.mozilla.org/en-US/firefox/)

**Comment by SDSDOS** [comment]
```
[localhost@localhost ~]$ sudo chrome-gnome-shell
[7899] Uncaught exception of type <type 'exceptions.TypeError'> occured
  File "/bin/chrome-gnome-shell", line 568, in <module>
    app = ChromeGNOMEShell(run_as_service)
  File "/bin/chrome-gnome-shell", line 82, in __init__
    None)
[7899] Exception: Argument 0 does not allow None as a value

(process:7899): GLib-GIO-CRITICAL **: g_application_release: assertion 'application->priv->use_count > 0' failed
```

The error occurrs only if I execute "sudo chrome-gnome-shell" while "chrome-gnome-shell" works fine.

**Comment by SDSDOS** [comment]
Any ideas on how to fix this?

**Comment by nE0sIghT** [comment]
Symlink "/usr/lib64/mozilla/native-messaging-hosts" -> "/usr/lib/mozilla/native-messaging-hosts" for workaround.
Report this issue to Fedora's bugtracker.
