### ISSUE TITLE
Failed to synchronize extensions

### ISSUE THREAD

**Issue by hackel** [nE0sIghT/chrome-gnome-shell-mirror#80]
Recently, whenever I start Chromium, I eventually get the following notification:
```
GNOME Shell integration
Failed to synchronize extensions:
GDBus.Error:org.gnome.Shell.DownloadInfoError: 404
```
I have been unable to find any information on this issue searching online.  The extension still seems to work fine. https://extensions.gnome.org/local/ shows all of my installed extensions and I can update them.  I primarily use Firefox as my primary browser, and it's working fine there, too.  Any insights?

**Comment by nE0sIghT** [comment]
Go to Chrome extension options and show synchronization tab:
![selection_032](https://user-images.githubusercontent.com/3389586/30840512-cbaf29c4-a288-11e7-8631-672f69084140.png)

**Comment by nE0sIghT** [comment]
Reopen and provide requested information if it still issue for you.

**Comment by Vadim-Stupakov** [comment]
Have the same issue

**Comment by nE0sIghT** [comment]
@Vadim-Stupakov 

Go to Chrome extension options and show synchronization tab:

![selection_032](https://user-images.githubusercontent.com/3389586/30840512-cbaf29c4-a288-11e7-8631-672f69084140.png)

**Comment by Vadim-Stupakov** [comment]
![screenshot from 2018-02-13 09-35-23](https://user-images.githubusercontent.com/11485451/36138250-54ebaeb6-10a1-11e8-9e11-cf10bca153a9.png)

**Comment by nE0sIghT** [comment]
@Vadim-Stupakov 

What is not working for you? Describe your use-case.

**Comment by Vadim-Stupakov** [comment]
Actually, I don't know. I don't have time to check what doesn't properly work (I have a lot of extensions)
But I have regular notification: "
GNOME Shell integration
Failed to synchronize extensions:
GDBus.Error:org.gnome.Shell.DownloadInfoError: 404"

And I think that it isn't correct work, isn't it?

**Comment by nE0sIghT** [comment]
@Vadim-Stupakov 

Which browser extension version do you using?
Latest version 10 should not produce error notifications.

**Comment by nE0sIghT** [comment]
Ok, for what I see some of your extensions could not be installed by GNOME Shell because of HTTP/404 error.
Since you don't have time to debug this issue you may just disable GNOME Shell extensions synchronization in browser extension's options.

The real fix for errors noise in Shell notifications will go to master branch soon

**Comment by Vadim-Stupakov** [comment]
Thank you. I came home, and found that I don't have such problem on home pc (with the same ubuntu and google chrome version)
How can I provide you version? (chrome-gnome-shell --help-all shows nothing)

**Comment by wsxy162** [comment]
Using Firefox's gnome-shell extension with version 10. My last synchronization marked all extensions being check, and now I have use the same Firefox account on a new OS, but the synchronization doesn't start. Trying install a extension to activate the synchronization, it didn't work.

**Comment by nE0sIghT** [comment]
@wsxy162 

Create new issue, provide screenshot of synchronization tab on both PCs.
Also: did you enabled Firefox Sync?

**Comment by nE0sIghT** [comment]
Reopen and provide requested info if it's still issue for you.

**Comment by MananDesai54** [comment]
after installing `sudo apt-get install build-essential dkms linux-headers-$(uname -r)` it worked so i think i had issue with tools not available to install the extension

**Comment by nE0sIghT** [comment]
@MananDesai54 

Package you posted are not related to chrome-gnome-shell.
