### ISSUE TITLE
"An unexpected error occurred"

### ISSUE THREAD

**Issue by luiztsmendes** [nE0sIghT/chrome-gnome-shell-mirror#82]
Firefox 52.0.2, Ubuntu precise 12.04 32 bits, gnome-shell 3.4.1.

After upgrading the "python-requests" package to version 2.3.0 in precise, installation of the chrome-gnome-shell connector went smoothly and with no errors. However, when trying to access the "installed extensions" gnome shell website, the message "An unexpected error occurred" is shown on top of the web page. No error message is present in the system logs. But when executing firefox from a terminal window, the following messages are shown:

1508076408007	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.

1508076408014	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing externally_connectable: An unexpected property was found in the WebExtension manifest.

1508076408014	addons.webextension.chrome-gnome-shell@gnome.org	WARN	Loading extension 'chrome-gnome-shell@gnome.org': Reading manifest: Error processing optional_permissions: An unexpected property was found in the WebExtension manifest.

**Comment by nE0sIghT** [comment]
Ubuntu 12.04 is not supported.
How did you installed chrome-gnome-shell? Which version?

**Comment by luiztsmendes** [comment]
Well, too bad it isn't supported ... but I can't blame the nE0sIghT team. I have another computer with Ubuntu 14.04 and the connector works flawlessly.

I installed the chrome-gnome-shell by following the instructions at the Chrome Webstore, namely

  sudo add-apt-repository ppa:ne0sight/chrome-gnome-shell
  sudo apt-get update
  sudo apt-get install chrome-gnome-shell

I had first to upgrade the "python-requests" package in Ubuntu 12.04. The chrome-gnome-shell version as reported by the Synaptic tool is 8-0ubuntu2.

**Comment by nE0sIghT** [comment]
> I installed the chrome-gnome-shell by following the instructions at the Chrome Webstore

It's a bit outdated because chrome-gnome-shell is available in main Ubuntu repositories some time.
You should not use PPA anymore.

Try to remove PPA, "apt-get purge chrome-gnome-shell" and then reinstall package from Universe repository [1].

[1] https://launchpad.net/ubuntu/+source/chrome-gnome-shell

**Comment by luiztsmendes** [comment]
I had already tried to install it from git, but gave up since the compilation failed due to the fact that the 'jq' tool for Ubuntu 12.04 from the precise repository is outdated.

But today, while inspecting the 'jq' website, I noticed that the 'jq' does not have any dependencies and so the newest version should compile in any platform. Then I downloaded the jq 1.5 source tarball and compiled and installed it successfully.

Next I compiled and installed chrome-gnome-shell from git with no problems at all. Unfortunately, the problem persists. When starting Firefox from a terminal, the same error messages previously reported appear.

**Comment by nE0sIghT** [comment]
Extensions website works well In Chrome?
Try to run Firefox with "--jsconsole" option to open browser console - are there any errors in browser console?

**Comment by luiztsmendes** [comment]
**Chrome:**

"Native host has exited" is shown on top of the web page. When starting it from a terminal, I get the following error messages:

[3639] Uncaught exception of type <type 'exceptions.TypeError'> occured
  File "/usr/bin/chrome-gnome-shell", line 585, in <module>
    app = ChromeGNOMEShell(run_as_service)
  File "/usr/bin/chrome-gnome-shell", line 73, in __init__
    self.register()
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
[3639] Exception: register() takes exactly 2 arguments (1 given)
[3644] Uncaught exception of type <type 'exceptions.TypeError'> occured
  File "/usr/bin/chrome-gnome-shell", line 585, in <module>
    app = ChromeGNOMEShell(run_as_service)
  File "/usr/bin/chrome-gnome-shell", line 73, in __init__
    self.register()
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
[3644] Exception: register() takes exactly 2 arguments (1 given)
[3643] Uncaught exception of type <type 'exceptions.TypeError'> occured
  File "/usr/bin/chrome-gnome-shell", line 585, in <module>
    app = ChromeGNOMEShell(run_as_service)
  File "/usr/bin/chrome-gnome-shell", line 73, in __init__
    self.register()
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
[3643] Exception: register() takes exactly 2 arguments (1 given)

**firefox --jsconsole:**

The following messages appear in the javascript console:

stderr output from native app org.gnome.chrome_gnome_shell: [4204] Uncaught exception of type <type 'exceptions.TypeError'> occured
stderr output from native app org.gnome.chrome_gnome_shell:   File "/usr/bin/chrome-gnome-shell", line 585, in <module>
stderr output from native app org.gnome.chrome_gnome_shell:     app = ChromeGNOMEShell(run_as_service)
stderr output from native app org.gnome.chrome_gnome_shell:   File "/usr/bin/chrome-gnome-shell", line 73, in __init__
stderr output from native app org.gnome.chrome_gnome_shell:     self.register()
stderr output from native app org.gnome.chrome_gnome_shell:   File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
stderr output from native app org.gnome.chrome_gnome_shell:     return info.invoke(*args, **kwargs)
stderr output from native app org.gnome.chrome_gnome_shell: [4204] Exception: register() takes exactly 2 arguments (1 given)
stderr output from native app org.gnome.chrome_gnome_shell: [4203] Uncaught exception of type <type 'exceptions.TypeError'> occured
stderr output from native app org.gnome.chrome_gnome_shell:   File "/usr/bin/chrome-gnome-shell", line 585, in <module>
stderr output from native app org.gnome.chrome_gnome_shell:     app = ChromeGNOMEShell(run_as_service)
stderr output from native app org.gnome.chrome_gnome_shell:   File "/usr/bin/chrome-gnome-shell", line 73, in __init__
stderr output from native app org.gnome.chrome_gnome_shell:     self.register()
stderr output from native app org.gnome.chrome_gnome_shell:   File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
stderr output from native app org.gnome.chrome_gnome_shell:     return info.invoke(*args, **kwargs)
stderr output from native app org.gnome.chrome_gnome_shell: [4203] Exception: register() takes exactly 2 arguments (1 given)

**Comment by nE0sIghT** [comment]
Open /usr/bin/chrome-gnome-shell in any editor as root user.
Go to line 73 and change line
```
        self.register()
```
to
```
        self.register(None)
```

**Comment by luiztsmendes** [comment]
Still not working.
After this change the error messages seem to be a little different (see below).
A side effect of this change is that somehow I got all my installed gnome-shell extensions reset, but I managed to get them back.

Chrome:

[2710] Uncaught exception of type <class 'gi._glib.GError'> occured
  File "/usr/bin/chrome-gnome-shell", line 585, in <module>
    app = ChromeGNOMEShell(run_as_service)
  File "/usr/bin/chrome-gnome-shell", line 73, in __init__
    self.register(None)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
[2711] Uncaught exception of type <class 'gi._glib.GError'> occured
  File "/usr/bin/chrome-gnome-shell", line 585, in <module>
    app = ChromeGNOMEShell(run_as_service)
  File "/usr/bin/chrome-gnome-shell", line 73, in __init__
    self.register(None)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
[2710] Exception: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
    return info.invoke(*args, **kwargs)
[2711] Exception: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)
[2750] Uncaught exception of type <class 'gi._glib.GError'> occured
  File "/usr/bin/chrome-gnome-shell", line 585, in <module>
    app = ChromeGNOMEShell(run_as_service)
  File "/usr/bin/chrome-gnome-shell", line 73, in __init__
    self.register(None)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
[2750] Exception: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)

Firefox:

stderr output from native app org.gnome.chrome_gnome_shell: [3552] Uncaught exception of type <class 'gi._glib.GError'> occured
stderr output from native app org.gnome.chrome_gnome_shell:   File "/usr/bin/chrome-gnome-shell", line 585, in <module>
stderr output from native app org.gnome.chrome_gnome_shell:     app = ChromeGNOMEShell(run_as_service)
stderr output from native app org.gnome.chrome_gnome_shell:   File "/usr/bin/chrome-gnome-shell", line 73, in __init__
stderr output from native app org.gnome.chrome_gnome_shell:     self.register(None)
stderr output from native app org.gnome.chrome_gnome_shell:   File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
stderr output from native app org.gnome.chrome_gnome_shell:     return info.invoke(*args, **kwargs)
stderr output from native app org.gnome.chrome_gnome_shell: [3552] Exception: GDBus.Error:org.freedesktop.DBus.Error.NoReply: Message did not receive a reply (timeout by message bus)

**Comment by nE0sIghT** [comment]
I think this may be some bug in old gobject bindings or some DBus misconfiguration.
Last time I checked there are was no issues in fully upgraded Ubuntu 12.04.

As I said Ubuntu 12.04 is not supported anymore and there is not such issue exists in supported versions, therefore I will not investigate it further.
I recommend you to upgrade your OS to supported LTS version.

**Comment by luiztsmendes** [comment]
Thanks anyway for your good work of providing gnome shell integration through the chrome-gnome-shell native connector.

As a workaround I installed FF 51.0.1 - for which still there is support for gnome shell integration in the old way (without need of the native connector) - alongside FF 52.0.2, by creating two different profiles for the same user (me). In this way, whenever I need to check or enable/disable my installed gnome shell extensions, I start FF 51.0.1 with its specific profile. Not the best solution but it works until Ubuntu 18.04 is out to upgrade my box.

**Comment by GianniGi** [comment]
same on ubuntu 22.04

firefox gnome extension installed
