### ISSUE TITLE
incorrectly installs on arch linux weird interaction with miniconda/python environment.

### ISSUE THREAD

**Issue by james-lawrence** [nE0sIghT/chrome-gnome-shell-mirror#83]
not sure if this is a packaging issue in arch linux, or something in the native build process. but thought I'd file it here and with the package just in case. [package in question](https://aur.archlinux.org/packages/chrome-gnome-shell-git)

during install the script `/usr/bin/chrome-gnome-shell` incorrectly sets the executable python on my system resulting in extensions.gnome.org claiming 'an unexpected error occurred'

on my system its picking up my user's local miniconda python version and not the system version.

cat /usr/bin/chrome-gnome-shell | head
#!/home/user/miniconda3/bin/python

by changing it to
#!/usr/bin/python

the script begins to work again.

**Comment by nE0sIghT** [comment]
> not sure if this is a packaging issue in arch linux

It's for sure packaging issue
