### ISSUE TITLE
Native host exited

### ISSUE THREAD

**Issue by dmitry-saritasa** [nE0sIghT/chrome-gnome-shell-mirror#84]
exceptions.py:2:<module>:ModuleNotFoundError: No module named 'urllib3.packages.six'

/usr/bin/python3 /usr/bin/chrome-gnome-shell /usr/lib64/mozilla/native-messaging-hosts/org.gnome.chrome_gnome_shell.json chrome-gnome-shell@gnome.org

So I had to downgrade requests to requests==2.5.0 from requests==2.18.1, then it started to work
```
[root@localhost ~]# uname -a
Linux localhost.localdomain 4.13.9-300.fc27.x86_64 #1 SMP Mon Oct 23 13:41:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@localhost ~]# 
```

**Comment by nE0sIghT** [comment]
Report this to Fedora's bugtracker.
