### ISSUE TITLE
Extension's icon hard to see in "Dark mode"

### ISSUE THREAD

**Issue by AdamKane41** [nE0sIghT/chrome-gnome-shell-mirror#85]
Should have choice of "light" or "dark" icon variants or light outline  around the icon to make it easier to see in "Dark mode" or dark themes. 
![screenshot from 2017-12-29 16-42-06](https://user-images.githubusercontent.com/30092603/34448209-53ad4570-ecb9-11e7-95fd-c6c5b5fc521a.png)

**Comment by nE0sIghT** [comment]
It would be helpfull if you will provide dark-theme icon variant.
