### ISSUE TITLE
Translation wiki page: mention GNOME Damend Lies

### ISSUE THREAD

**Issue by josephgbr** [nE0sIghT/chrome-gnome-shell-mirror#9]
Currently, [Translation process wiki page](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Translations) provides some (nice) info on how to create/update PO file manually.

I don't know if that's exclusive, but translation for chrome-gnome-shell take place in GNOME's translation platform, [Damned Lies](https://l10n.gnome.org/module/chrome-gnome-shell/), in a very organized way.  So, my suggestion is to **firstly** mention translation in D-L, encouraging contributors to sign up and join translation and, alternatively, run the manual process (which is already documented).

**Comment by nE0sIghT** [comment]
Described process is fully compatible with DL. Moreover it's created especially to support DL :-)
I added some more info about GNOME Translation Project and DL.
Since this is open wiki feel free to improve this information :-)
