### ISSUE TITLE
Extension displays release notes when upgraded

### ISSUE THREAD

**Issue by twm** [nE0sIghT/chrome-gnome-shell-mirror#90]
This extension periodically opens a tab containing its release notes. This new tab opened in the foreground when doing other things, and its opening has no apparent causal connection to an action I have taken as a user.

Please don't open the release notes when the extension is upgraded. It interrupts me when I was doing something else, which is upsetting.

Browser: Firefox 58.0.2
GNOME Shell integration: 10.1

**Comment by nE0sIghT** [comment]
Disable this behavior in browser.

![selection_038](https://user-images.githubusercontent.com/3389586/37751166-5c7a3b0e-2daa-11e8-9091-3deeab1fb624.png)
![selection_039](https://user-images.githubusercontent.com/3389586/37751169-5feb23c0-2daa-11e8-932b-36eb9e32ca2e.png)

extensions's options.
