### ISSUE TITLE
Uninstall 

### ISSUE THREAD

**Issue by Spintendo** [nE0sIghT/chrome-gnome-shell-mirror#91]
How do I uninstall Gnome shell Integration from Chromium? The following resolution did not work for me: 
   "Remove uninstalled policy files which the package manager did not address:
   rm /etc/opt/chrome/policies/managed/chrome-gnome-shell.json 
   rm /etc/chromium/policies/managed/chrome-gnome-shell.json"

Please advise on how to remove this extension.

**Comment by nE0sIghT** [comment]
Are you sure policy files were removed?
Please show output of 
```
ls -l /etc/opt/chrome/policies/managed/
ls -l /etc/chromium/policies/managed/
```

**Comment by Spintendo** [comment]
total 4
-rw-r--r-- 1 root root 218 May  4  2017 chrome-gnome-shell.json
 
I don't have chrome installed.

**Comment by nE0sIghT** [comment]
As you can see - you do not removed policies.
Delete them and extension will gone.

**Comment by Spintendo** [comment]
Which takes us back to my original question. How do you delete the policies.
