### ISSUE TITLE
Configure and Uninstall buttons won't appear directly after a new install

### ISSUE THREAD

**Issue by Eskander** [nE0sIghT/chrome-gnome-shell-mirror#92]
After installing a new extension, Configure and Uninstall buttons (aka extra-buttons) won't appear automatically and a page reload is needed for them to appear.
I believe `window.location.reload(false)` after the user clicks Install on the popup would be a quick fix.

**Comment by nE0sIghT** [comment]
Which browser do you use?

**Comment by Skqnder** [comment]
Google Chrome 65 on Ubuntu 18.04
