### ISSUE TITLE
Failed to install unpacked extension

### ISSUE THREAD

**Issue by Cordifhyura** [nE0sIghT/chrome-gnome-shell-mirror#93]
While got a git clone and have connector installed.I failed to install unpacked extension under "extension" folder in chrome-gnome-shell directory on Chromium.Here's the issue:
> Failed to load extension from: /home/ducanoidyoung/chrome-gnome-shell/extension
Value 'key' is missing or invalid.

Using Chromium 65 on ubuntu 18.04

**Comment by nE0sIghT** [comment]
Why do you think it should work?
Build extension first using cmake as described in [Installation guide [1]](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation#Cmake_installation), but do not pass ```-DBUILD_EXTENSION=OFF``` option.
Ready to use extensions for Chrome/Firefox/Opera will be in ```build``` folder.

Feel free to reopen this issue if you have any questions.

[1] https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/Installation#Cmake_installation

**Comment by Cordifhyura** [comment]
Found a python script named `chrome-gnome-shell` in `build` folder after built extension.
![image](https://user-images.githubusercontent.com/27038451/39696941-e17b33da-5221-11e8-9b69-39d948d31b1c.png)
Got no idea about what's going to do next.Should I unpack it or something goes wrong?

**Comment by nE0sIghT** [comment]
What command did you used to build extension?
Also post command output here.

**Comment by Cordifhyura** [comment]
`cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_EXTENSION=OFF ../`
-- Found base64: /usr/bin/base64
-- Found sha256sum: /usr/bin/sha256sum
-- Found ghead: /usr/bin/head
-- Found tr: /usr/bin/tr
-- Found jq: /usr/bin/jq
-- Calculated Chrome extension id: gphhapmejobijbbhgpjhcjognlahblep
-- Calculated Opera extension id: olkooankbfblcebocnkjganpdmflbnbk
-- Found PythonInterp: /usr/bin/python (found version "2.7.15") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ducanoidyoung/chrome-gnome-shell/build
`sudo make install`
Scanning dependencies of target firefox-native-manifest
Built target firefox-native-manifest
Scanning dependencies of target build-connector
running build
running build_scripts
creating build
creating build/scripts-2.7
copying and adjusting /home/ducanoidyoung/chrome-gnome-shell/connector/../build/chrome-gnome-shell -> build/scripts-2.7
changing mode of build/scripts-2.7/chrome-gnome-shell from 644 to 755
Built target build-connector
Install the project...
-- Install configuration: ""
running install
running build
running build_scripts
running install_scripts
copying build/scripts-2.7/chrome-gnome-shell -> /usr/bin
changing mode of /usr/bin/chrome-gnome-shell to 755
running install_egg_info
Removing /usr/lib/python2.7/site-packages/chrome_gnome_shell-0.0.0-py2.7.egg-info
Writing /usr/lib/python2.7/site-packages/chrome_gnome_shell-0.0.0-py2.7.egg-info
-- Installing: /etc/chromium/native-messaging-hosts/org.gnome.chrome_gnome_shell.json
-- Installing: /etc/opt/chrome/native-messaging-hosts/org.gnome.chrome_gnome_shell.json
-- Installing: /usr/lib/mozilla/native-messaging-hosts/org.gnome.chrome_gnome_shell.json
-- Up-to-date: /usr/share/applications/org.gnome.ChromeGnomeShell.desktop
-- Installing: /usr/share/dbus-1/services/org.gnome.ChromeGnomeShell.service
-- Up-to-date: /usr/share/icons/gnome/16x16/apps/org.gnome.ChromeGnomeShell.png
-- Up-to-date: /usr/share/icons/gnome/48x48/apps/org.gnome.ChromeGnomeShell.png
-- Up-to-date: /usr/share/icons/gnome/128x128/apps/org.gnome.ChromeGnomeShell.png

**Comment by nE0sIghT** [comment]
As I said before - do not pass ```-DBUILD_EXTENSION=OFF``` option to cmake.

Your build command should be

```cmake -DCMAKE_INSTALL_PREFIX=/usr ../```

or

```cmake -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_CONNECTOR=OFF ../```

if you do not need connector

**Comment by Cordifhyura** [comment]
Sorry for misunderstanding but here's the new issue:
`cmake -DCMAKE_INSTALL_PREFIX=/usr ../`
-- Found base64: /usr/bin/base64
-- Found sha256sum: /usr/bin/sha256sum
-- Found ghead: /usr/bin/head
-- Found tr: /usr/bin/tr
-- Found jq: /usr/bin/jq
-- Calculated Chrome extension id: gphhapmejobijbbhgpjhcjognlahblep
-- Calculated Opera extension id: olkooankbfblcebocnkjganpdmflbnbk
CMake Error at CMakeLists.txt:66 (message):
  Could NOT find 7z.
Call Stack (most recent call first):
  CMakeLists.txt:118 (find_program_ex)


-- Configuring incomplete, errors occurred!
See also "/home/ducanoidyoung/chrome-gnome-shell/build/CMakeFiles/CMakeOutput.log".
`CMakeOutput.log`
The system is: Linux - 4.15.0-20-generic - x86_64

**Comment by nE0sIghT** [comment]
Just install p7zip

**Comment by Cordifhyura** [comment]
Thanks,now I got the extension,and have the connector built.
But right now my connector can't be detected.
Should I do some additional settings?

**Comment by nE0sIghT** [comment]
> Should I do some additional settings to open the connector?

Nothing special. It should be just installed.
Using distro package or manually.

**Comment by nE0sIghT** [comment]
Feel free to reopen this issue if you have any questions.
