### ISSUE TITLE
A nasty bug which finally found in Firefox gnome-shell-integration!!!

### ISSUE THREAD

**Issue by Bonsitar** [nE0sIghT/chrome-gnome-shell-mirror#95]
Hey there.
(I apologize for using bad words in title ("nasty"), I used it because honestly it is...)

Three or four month ago I had a problem with gnome-shell. That days when I log-in to my gnome desktop (after entering password in gdm...) all of my installed and active extensions switched "off" automatically! And after a lot of effort I finally found the reason. The [Mozilla Firefox gnome-shell-integration add-on](https://addons.mozilla.org/en-US/firefox/addon/gnome-shell-integration/?src=search) was the cause of this problem! Why? How I was able to find it?
Well, When firefox starts the problem starts occurring, so the problem should be one of firefox parts that is related to gnome-shell, thus I searched for it and realized that when this extension is removed that problem won't occur. 
And another thing should be mentioned here is this problem will shown itself not always but in some period of time (Three or four month ago and yesterday this problem occurred on my machine) maybe it is related to upgrades of the add-on.
Uh-huh here is another fact that the gnome-shell-integration in Google-Chrome browser doesn't have any of this problem so its related to firefox and it's extension!
Finally here is a quick screen record of problem in firefox:
https://imgur.com/zKgDpmb
(When add-on in firefox browser set off, all of active extension back to their previous status and no more problem! But when I switch add-on to "On" it sets off all extensions in gnome-shell (included user theme that provide the shell theme).
Woops! I forgot to mention my friend (@hedayat) knows about this problem and he is more technical than me so he may have a opinion about this subject :D.

Regards.

**Comment by nE0sIghT** [comment]
Hello.

Did you have synchronization enabled? If so, it's expected behavior.

GNOME Shell integration saves GNOME Shell extensions state so if GNOME Shell integration is disabled and you change GNOME Shell extensions state using other application, then upon enabling GNOME Shell integration will restore known GNOME Shell extensions state.

![selection_041](https://user-images.githubusercontent.com/3389586/42128177-79d0dd6a-7cb6-11e8-8e65-6068e1f19fd0.png)

**Comment by Bonsitar** [comment]
Oops! I didn't know that. On the other hand I've this extension in my Google-Chrome with same configuration as Firefox, So why it didn't happen in Chrome!? (I don't have any of this problem with chrome and its extension!)

**Comment by nE0sIghT** [comment]
Are you sure that your issue is not related to PC sleep/hibernate?
There is [known problem with sleep/hibernate](https://github.com/nE0sIghT/chrome-gnome-shell-mirror/issues/45) that is have work around in Chrome, but does not have work around in Firefox currently.

**Comment by Bonsitar** [comment]
Hmmm. I didn't have any problem with Chrome's extension so far! AFAIK it just occurs in Firefox. And about PC sleep/hibernate, As far as I remember I hadn't any problem during sleeps or hibernates.

**Comment by nE0sIghT** [comment]
I'm not sure what is the problem you experience.

Please write complete steps to reproduce this issue, eg
1. Install browser extension
2. Open GNOME Tweak tool
3. Disable any GNOME Shell extension using Tweak tool
4. ...

**Comment by nE0sIghT** [comment]
Reopen if you still experience this issue and provide requested info.
