### ISSUE TITLE
native host connector is not detected ( on debian )

### ISSUE THREAD

**Issue by MagdyA** [nE0sIghT/chrome-gnome-shell-mirror#96]
I have tried reinstalling both `chrome` and the package `chrome-gnome-shell` 
but still get the error message 

> Although GNOME Shell integration extension is running, native host connector is not detected. Refer documentation for instructions about installing connector.

I believe it's some sort of wrong file location configuration.

I'm running Debian stretch ( stable ) x86_64
any help would be appreciated

**Comment by nE0sIghT** [comment]
Which version of chrome-gnome-shell do you using?

Debian does not support Google Chrome with chrome-gnome-shell's older versions.
Look to Debian's bug https://bugs.debian.org/840804

**Comment by MagdyA** [comment]
I'm using package version 8.4

**Comment by nE0sIghT** [comment]
So you are affected by https://bugs.debian.org/840804.
You can symlink ```/etc/chromium``` to ```/etc/opt/chrome``` for a workaround.
