### ISSUE TITLE
Unable to check for updates - bad gateway

### ISSUE THREAD

**Issue by glitsj16** [nE0sIghT/chrome-gnome-shell-mirror#97]
Hi, I have been unable to check for updates for a while now. More detailed info on OS, installed versions etcetera:

OS: Arch Linux (fully updated)
$ pacman -Q chrome-gnome-shell firefox
chrome-gnome-shell 10.1-2
firefox 64.0.2-1

Firefox addon
GNOME Shell integration 10.1

Browser console output with DEBUG_ENABLED = True

= = =
03:02:54.547
502 Server Error: Bad Gateway for url: https://extensions.gnome.org/update-info/… update.js:48:9
03:02:54.559 stderr output from native app org.gnome.chrome_gnome_shell: [286] Main. Use Ctrl+D to quit.
03:02:54.559 stderr output from native app org.gnome.chrome_gnome_shell: [286] On input
03:02:54.559 stderr output from native app org.gnome.chrome_gnome_shell: [286] Execute: to checkUpdate
03:02:54.559 stderr output from native app org.gnome.chrome_gnome_shell: [286] Unable to check extensions updates: 502 Server Error: Bad Gateway for url: https://extensions.gnome.org/update-info/?shell_version=3.30.2&installed=%7B%22window_buttons%40biox.github.com%22%3A+%7B%22version%22%3A+15%7D%2C+%22forcegc%40email.com%22%3A+%7B%22version%22%3A+1%7D%2C+%22middleclickclose%40paolo.tranquilli.gmail.com%22%3A+%7B%22version%22%3A+14%7D%2C+%22dash-to-dock%40micxgx.gmail.com%22%3A+%7B%22version%22%3A+64%7D%2C+%22apt-update-indicator%40franglais125.gmail.com%22%3A+%7B%22version%22%3A+20%7D%2C+%22mediaplayer%40patapon.info%22%3A+%7B%22version%22%3A+63%7D%2C+%22noannoyance%40sindex.com%22%3A+%7B%22version%22%3A+3%7D%2C+%22tint-all%40amarovita.github.com%22%3A+%7B%22version%22%3A+4%7D%2C+%22appindicatorsupport%40rgcjonas.gmail.com%22%3A+%7B%22version%22%3A+22%7D%2C+%22workspace-switcher-wrapAround%40wrowclif.org%22%3A+%7B%22version%22%3A+4%7D%2C+%22windows-blur-effects%40com.gmail.lviggiani%22%3A+%7B%22version%22%3A+12%7D%2C+%22openweather-extension%40jenslody.de%22%3A+%7B%22version%22%3A+97%7D%2C+%22argos%40pew.worldwidemann.com%22%3A+%7B%22version%22%3A+2%7D%2C+%22TopIcons%40huttli%22%3A+%7B%22version%22%3A+21%7D%2C+%22workspaces-to-dock%40passingthru67.gmail.com%22%3A+%7B%22version%22%3A+49%7D%2C+%22pixel-saver%40deadalnix.me%22%3A+%7B%22version%22%3A+15%7D%2C+%22CoverflowAltTab%40dmo60.de%22%3A+%7B%22version%22%3A+1%7D%2C+%22battery_status%40milliburn.github.com%22%3A+%7B%22version%22%3A+10%7D%2C+%22indicator-sensors%40alexmurray.github.com%22%3A+%7B%22version%22%3A+5%7D%2C+%22widget_blocker%40isacdaavid%22%3A+%7B%22version%22%3A+5%7D%2C+%22hide-Brightness%40xzs%22%3A+%7B%22version%22%3A+1%7D%2C+%22hide-Battery%40xzs%22%3A+%7B%22version%22%3A+1%7D%2C+%22overview-titles%40naheel.com%22%3A+%7B%22version%22%3A+2%7D%2C+%22disable-workspace-switcher-popup%40github.com%22%3A+%7B%22version%22%3A+2%7D%2C+%22hide-User%40xzs%22%3A+%7B%22version%22%3A+1%7D%2C+%22suspend-button%40laserb%22%3A+%7B%22version%22%3A+20%7D%7D
03:02:54.559 stderr output from native app org.gnome.chrome_gnome_shell: [286] Execute: from checkUpdate
03:02:54.559 stderr output from native app org.gnome.chrome_gnome_shell: [286] On hup: <flags G_IO_HUP of type GLib.IOCondition>
03:02:54.559 stderr output from native app org.gnome.chrome_gnome_shell: [286] Release
03:02:54.559 stderr output from native app org.gnome.chrome_gnome_shell: [286] Quit

Please feel free to ask if I can provide more details.

Regards

**Comment by nE0sIghT** [comment]
The fix for this issue is currently deployed. it should be fixed within several minutes.

**Comment by nE0sIghT** [comment]
How many installed extensions do you have?

**Comment by glitsj16** [comment]
@nE0sIghT Thanks for the speedy fix, I can confirm things are working again as expected.

Total number of installed extensions: 30 (9 disabled).

I run Arch Linux as my main distro, but am double-booting with Ubuntu 16.04 LTS. Sharing locally installed extensions via symlinking to a shared partition. Hence I have a few Ubuntu specific ones which are kept disabled on Arch. Here's a detailed overview.

System-wide (/usr/share/gnome-shell/extensions):

    [01] activities-config@nls1729 [[from here](https://aur.archlinux.org/packages/gnome-shell-extension-activities-config/)]
    [02] transmission-daemon@patapon.info [[from here](https://aur.archlinux.org/packages/gnome-shell-extension-transmission-daemon-git/)]
    [03*] auto-move-windows@gnome-shell-extensions.gcampax.github.com (disabled)
    [04*] user-theme@gnome-shell-extensions.gcampax.github.com

locally (~/.local/share/gnome-shell/extensions, shared with ubuntu):

    [05] appindicatorsupport.com (ubuntu only)
    [06] apt-update-indicator (ubuntu only)
    [07] argos
    [08] battery_status
    [09] CoverflowAltTab
    [10] dash-to-dock
    [11] disable-workspace-switcher-popup
    [12] forcegc (disabled)
    [13] hide-battery
    [14] hide-brightness
    [15] hide-user
    [16] indicator-sensors (disabled)
    [17] mediaplayer
    [18] middleclickclose
    [19] noannoyance
    [20] openweather-extension
    [21] overview-titles
    [22] pixel-saver
    [23] suspend-button
    [24] tint-all (disabled)
    [25] TopIcons
    [26] widget_blocker
    [27] window_buttons (disabled on Arch)
    [28] windows-blur-effects
    [29] workspaces-to-dock
    [30] workspace-switcher-wrapAround

[*] These are part of the [gnome-shell-extensions](https://www.archlinux.org/packages/extra/any/gnome-shell-extensions/) package on Arch Linux. That package includes 11 more extensions, which I keep uninstalled via pacman's NoExtract mechanism. Otherwise the count would be higher. Whether or not this is a high amount of extensions I cannot judge. I have been running these for a few years now, so this is my 'stable' set of extensions I'd say. More importantly, the above extensions (and their configuration) keep gnome-shell running *very* stable and smooth (on average consuming around 5% CPU and MEM), which makes using GNOME simply a joy. 

Hope this helps.

**Comment by glitsj16** [comment]
@nE0sIghT After building chrome-gnome-shell from git master, I now am getting a different error, disabling extension update checks yet again.

OS: Arch Linux (fully updated)
$ pacman -Q chrome-gnome-shell firefox
chrome-gnome-shell 10.1+15+g37ba2ea-1
firefox 64.0.2-1

Firefox addon
GNOME Shell integration 10.1

Browser console output with DEBUG_ENABLED = True

= = =

stderr output from native app org.gnome.chrome_gnome_shell: [258] Main. Use Ctrl+D to quit.
16:02:09.114 stderr output from native app org.gnome.chrome_gnome_shell: [258] On input
16:02:09.114 stderr output from native app org.gnome.chrome_gnome_shell: [258] Execute: to initialize
16:02:09.114 stderr output from native app org.gnome.chrome_gnome_shell: [258] Execute: from initialize
16:02:09.114 stderr output from native app org.gnome.chrome_gnome_shell: [258] On hup: <flags G_IO_HUP of type GLib.IOCondition>
16:02:09.114 stderr output from native app org.gnome.chrome_gnome_shell: [258] Release
16:02:09.114 stderr output from native app org.gnome.chrome_gnome_shell: [258] Quit
16:02:09.490 stderr output from native app org.gnome.chrome_gnome_shell: [259] Main. Use Ctrl+D to quit.
16:02:09.490 stderr output from native app org.gnome.chrome_gnome_shell: [259] On input
16:02:09.490 stderr output from native app org.gnome.chrome_gnome_shell: [259] Execute: to listExtensions
16:02:09.490 stderr output from native app org.gnome.chrome_gnome_shell: [259] Execute: from listExtensions
16:02:09.490 stderr output from native app org.gnome.chrome_gnome_shell: [259] On hup: <flags G_IO_HUP of type GLib.IOCondition>
16:02:09.490 stderr output from native app org.gnome.chrome_gnome_shell: [259] Release
16:02:09.490 stderr output from native app org.gnome.chrome_gnome_shell: [259] Quit
16:02:27.578
403 Client Error: Forbidden for url: https://extensions.gnome.org/update-info/… update.js:48:9
16:02:27.595 stderr output from native app org.gnome.chrome_gnome_shell: [268] Main. Use Ctrl+D to quit.
16:02:27.595 stderr output from native app org.gnome.chrome_gnome_shell: [268] On input
16:02:27.595 stderr output from native app org.gnome.chrome_gnome_shell: [268] Execute: to checkUpdate
16:02:27.595 stderr output from native app org.gnome.chrome_gnome_shell: [268] Unable to check extensions updates: 403 Client Error: Forbidden for url: https://extensions.gnome.org/update-info/?shell_version=3.30.2
16:02:27.595 stderr output from native app org.gnome.chrome_gnome_shell: [268] Execute: from checkUpdate
16:02:27.595 stderr output from native app org.gnome.chrome_gnome_shell: [268] On hup: <flags G_IO_HUP of type GLib.IOCondition>
16:02:27.595 stderr output from native app org.gnome.chrome_gnome_shell: [268] Release
16:02:27.595 stderr output from native app org.gnome.chrome_gnome_shell: [268] Quit

Regards

**Comment by nE0sIghT** [comment]
It's expected since master branch of chrome-gnome-shell requires master branch of website which is not deployed.
You never should use master branch of chrome-gnome-shell for non-development purposes.

**Comment by glitsj16** [comment]
@nE0sIghT That makes sense, thank you for clearing that up. After reverting to 10.1-2 things are back to normal.
