### ISSUE TITLE
Kali gnome extensions "Native host exited"

### ISSUE THREAD

**Issue by playwime** [nE0sIghT/chrome-gnome-shell-mirror#99]
Hi all. Need a little help please.
Using Firefox I have no problems using gnome extensions via shell integration.
My problem came after wanting to switch to chrome. I downloaded chrome okay. Been default root user was solved using some terminal commands that instructed chrome to open as normal user in root signed in account, made a desktop icon, all was good and stopped the need to use a command to open chrome without sandbox each time and have full features.
So anyway running chrome, installing gnome shell integration, all good but native host exited always appears on gnome extensions. Chrome gnome shell is installed and up to date.
I was wondering if instructing chrome to open as normal user or having Firefox gnome extensions installed was the issue?

**Comment by nE0sIghT** [comment]
Make a symbolic link ```/etc/chromium → /etc/opt/chrome```. And report this to Kali.

See also: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=840804
